import test from 'node:test';
import assert from 'node:assert/strict';
import {parseDirectorCommand,directorPreferences,updateDirectorPreferences,directorInstruction,validateDirectorOutput} from '../src/chat/director.js';
import {emptyVault} from '../src/schema.js';
import {serializePortableBackup,parseVesperBackup} from '../src/backup/vesper-backup.js';
import {runTurn} from '../src/chat/turn-engine.js';
const fixture=()=>({...emptyVault(),personas:[{id:'p',name:'Player'}],characters:[{id:'x',name:'Character'}],stories:[{id:'s',title:'Synthetic Director',personaId:'p',characterIds:['x'],settings:{model:'synthetic/model',cnc:false,intimacyStyle:'balanced'}},{id:'other',title:'Other synthetic story',personaId:'p',characterIds:['x']}],chats:[{id:'c',storyId:'s'}],messages:[{id:'m',storyId:'s',chatId:'c',role:'user',text:'I look toward the door.',ordinal:0}]});
for(const [command,kind,detail] of [['/skip sleep','skip','sleep'],['/skip mundane','skip','mundane'],['/skip 3 hours','skip','3 hours'],['/skip 30 minutes','skip','30 minutes'],['/skip 20 seconds','skip','20 seconds'],['/skip 2 months','skip','2 months'],['/skip 1 year','skip','1 year'],['/event flirt','event','flirt'],['/event attack','event','attack'],['/event custom A visitor arrives.','custom','A visitor arrives.'],['/surprise','surprise','']])test('parses explicit '+command,()=>assert.deepEqual(parseDirectorCommand(command),{kind,detail}));
for(const command of ['/skip','/skip forever','/skip -2 hours','/skip 999 years','/event','/event custom','/event unknown','/surprise extras'])test('rejects invalid Director command '+command,()=>assert.throws(()=>parseDirectorCommand(command)));
test('ordinary dialogue and other existing commands are untouched',()=>{for(const text of ['I /skip sleep','/ooc hello','/continue','Hello'])assert.equal(parseDirectorCommand(text),null);});
test('defaults do not rewrite story and preferences stay independent',()=>{const v=fixture(),before=structuredClone(v);assert.deepEqual(directorPreferences(v.stories[0]),{intensity:'subtle',pacing:'cinematic'});assert.deepEqual(v,before);const next=updateDirectorPreferences(v,'s',{intensity:'chaotic',pacing:'immediate'});assert.deepEqual(next.stories[0].settings,{...before.stories[0].settings,director:{intensity:'chaotic',pacing:'immediate'}});assert.deepEqual(next.stories[1],before.stories[1]);for(const key of Object.keys(v).filter(k=>k!=='stories'))assert.deepEqual(next[key],before[key]);assert.deepEqual(directorPreferences(parseVesperBackup(serializePortableBackup(next)).stories[0]),{intensity:'chaotic',pacing:'immediate'});assert.throws(()=>updateDirectorPreferences(v,'s',{intensity:'invalid',pacing:'immediate'}));});
for(const command of ['/skip sleep','/skip mundane','/skip 3 hours','/event flirt','/event attack','/event custom A visitor arrives.','/surprise'])test('Director instruction preserves agency and canon: '+command,()=>{const text=directorInstruction(parseDirectorCommand(command),{intensity:'dramatic',pacing:'immediate'});assert.match(text,/Never write the protagonist/);assert.match(text,/hard limits/);assert.match(text,/consent/);assert.match(text,/milestone/);assert.match(text,/dramatic/);assert.match(text,/immediate/);if(command.startsWith('/skip'))assert.match(text,/offscreen/);});
test('Director output rejects predetermined protagonist consequences',()=>{for(const text of ['Player was captured.','Player was injured.','Player decided to run.','Player said "yes".'])assert.ok(validateDirectorOutput(text,{name:'Player'}).length);assert.equal(validateDirectorOutput('Character lunged toward the doorway, leaving a clear opening.',{name:'Player'}).length,0);});
test('Director one-request mode sends exact command without changing My Turn',async()=>{const v=fixture(),prior=structuredClone(v),fetch=globalThis.fetch,storage=globalThis.localStorage,calls=[];globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_,o)=>{calls.push(JSON.parse(o.body));return {ok:true,json:async()=>({choices:[{message:{content:'Player was captured.'}}]})};};try{const result=await runTurn({vault:v,storyId:'s',chatId:'c',model:'synthetic/model',director:true,oocInstruction:directorInstruction(parseDirectorCommand('/event attack'),directorPreferences(v.stories[0]))});assert.equal(calls.length,1);assert.equal(result.blocked,true);assert.equal(result.usage.length,1);assert.match(JSON.stringify(calls[0]),/attempted attack/);assert.deepEqual(v,prior);}finally{globalThis.fetch=fetch;if(storage===undefined)delete globalThis.localStorage;else globalThis.localStorage=storage;}});

async function mockDirector(v,response,options={}){
 const fetch=globalThis.fetch,storage=globalThis.localStorage,calls=[];globalThis.localStorage={getItem:()=> 'synthetic-key'};
 globalThis.fetch=async(_,o)=>{calls.push(JSON.parse(o.body));return {ok:true,json:async()=>({choices:[{message:{content:response}}]})};};
 try{return {result:await runTurn({vault:v,storyId:'s',chatId:'c',model:'synthetic/model',director:true,oocInstruction:directorInstruction(parseDirectorCommand('/skip sleep'),directorPreferences(v.stories[0])),...options}),calls};}
 finally{globalThis.fetch=fetch;if(storage===undefined)delete globalThis.localStorage;else globalThis.localStorage=storage;}
}
const sleepingValec=()=>{const v=fixture();v.personas[0].name='Amanda';v.personas[0].profile={age:30,species:'Human'};v.characters[0].name='Valec Thorne';v.characters[0].profile={age:38,species:'Shifter',personality:'Controlled, observant, dryly humorous'};v.messages[0].text='Amanda and Valec completed their mate bond.';v.milestones=[{id:'bond',storyId:'s',chatId:'c',type:'mated',participants:['p','x'],status:'confirmed',sourceMessageId:'m',evidence:v.messages[0].text,verification:{verified:true,completed:true,verifiedBy:'user'}}];v.messages.push({id:'sleep',storyId:'s',chatId:'c',role:'assistant',ordinal:1,text:'Valec and Amanda were already asleep together. Their established mate bond was unchanged.'});return v;};
for(const peaceful of ['They were already asleep together.','They rested in a peaceful embrace.','The completed mate bond settled into a quiet moment.'])test('peaceful Valec scene cannot end Director continuation: '+peaceful,async()=>{
 const v=sleepingValec();v.messages.at(-1).text=peaceful;const before=structuredClone(v);
 const {result,calls}=await mockDirector(v,'The story has reached a complete conclusion. No continuation is necessary.');
 assert.equal(result.blocked,true);assert.ok(result.issueTypes.includes('director-meta'));assert.equal(calls.length,1);assert.deepEqual(v,before);
 const final=calls[0].messages.at(-1);assert.equal(final.role,'system');assert.match(final.content,/already asleep/);assert.match(final.content,/not the end of the story/);assert.match(final.content,/Valec|NPC/);assert.match(final.content,/waking behavior/);assert.match(calls[0].messages[0].content,/"mateBondCanon":\{/);
});
for(const text of ['This story is complete.','No further continuation is needed.','There is no need to continue.','The narrative has reached its natural conclusion.','This scene needs no continuation.','As an AI, I cannot continue this roleplay.','The story reached a complete conclusion.','This is the end of the story.','From a narrative perspective, the scene is resolved.'])test('all Director actions reject ending commentary: '+text,async()=>{
 for(const command of ['/skip sleep','/skip mundane','/skip 3 hours','/event flirt','/event attack','/event custom A knock sounds.','/surprise']){const {result,calls}=await mockDirector(fixture(),text,{oocInstruction:directorInstruction(parseDirectorCommand(command),{intensity:'subtle',pacing:'cinematic'})});assert.equal(result.blocked,true,command);assert.equal(calls.length,1);}
});
test('NPC waking continuation keeps established canon and protagonist agency',async()=>{const v=sleepingValec(),before=structuredClone(v),{result,calls}=await mockDirector(v,'Morning light reached the room. Valec opened his eyes and listened to the quiet house.');assert.equal(result.blocked,false);assert.equal(calls.length,1);assert.deepEqual(v,before);assert.match(calls[0].messages.at(-1).content,/established relationship/);});
for(const text of ['Amanda woke up.','Amanda opened her eyes.','Amanda stirred awake.','You wake up.','You open your eyes.'])test('Director cannot choose protagonist waking behavior: '+text,async()=>assert.equal((await mockDirector(sleepingValec(),text)).result.blocked,true));
test('ordinary in-world uses of completion words are not meta refusals',async()=>{for(const text of ['Valec completed his morning report.','The bond was complete; morning light warmed the room.','"Our work is finished," Valec said, closing the folder.'])assert.equal((await mockDirector(sleepingValec(),text)).result.blocked,false);});
for(const state of [{status:'finished'},{status:'completed'},{finished:true},{completed:true}])test('explicit story completion stops before provider without rewriting state '+JSON.stringify(state),async()=>{const v=sleepingValec();Object.assign(v.stories[0],state);const before=structuredClone(v);await assert.rejects(()=>mockDirector(v,'Morning light filled the room.'),/explicitly marked|finished/i);assert.deepEqual(v,before);});
test('My Turn remains allowed to draft protagonist waking behavior',async()=>{const {result,calls}=await mockDirector(sleepingValec(),'Amanda opened her eyes.',{director:false,personaDraft:true,oocInstruction:'Draft an editable player turn.'});assert.equal(result.blocked,false);assert.equal(calls.length,1);});
test('other OOC tools do not accept story-ending commentary',async()=>{for(const instruction of ['[OOC: Continue the scene.]','[OOC: Elaborate the previous response.]','[OOC: Advance to the next morning.]']){const {result}=await mockDirector(fixture(),'The story has reached a complete conclusion.',{director:false,oocInstruction:instruction,repairAttempts:0});assert.equal(result.blocked,true);}});
