import asyncio,json,pathlib,threading,http.server,functools
from playwright.async_api import async_playwright
root=pathlib.Path(__file__).resolve().parents[1];server=http.server.ThreadingHTTPServer(('127.0.0.1',8798),functools.partial(http.server.SimpleHTTPRequestHandler,directory=str(root)));threading.Thread(target=server.serve_forever,daemon=True).start()
state="async()=>{const s=await import('./src/storage/vault-store.js');return s.loadVault(await s.openVesperDb());}"
async def run():
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox'])
  for device in ['Desktop','iPhone 13','iPad (gen 7)']:
   opts={} if device=='Desktop' else p.devices[device].copy();opts.pop('default_browser_type',None);ctx=await browser.new_context(**opts);page=await ctx.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
   await page.goto('http://127.0.0.1:8798/');await page.locator('.milestone-toast').wait_for(state='attached')
   await page.evaluate("""async()=>{const s=await import('./src/storage/vault-store.js'),db=await s.openVesperDb(),v=await s.loadVault(db);v.personas=[{id:'p',name:'Synthetic'}];v.characters=[{id:'x',name:'Synthetic'}];v.stories=[{id:'s',title:'Synthetic',personaId:'p',characterIds:['x']}];v.chats=[{id:'c',storyId:'s'},{id:'other-chat',storyId:'s'}];v.memoryEntries=[{id:'stale',storyId:'s',chatId:'c',kind:'summary',status:'active',text:'STALE_BLUE_BOX',sourceMessageIds:['m']},{id:'safe',storyId:'s',kind:'canon',text:'SAFE_UNRELATED_CANON',status:'active'}];v.messages=[{id:'m',storyId:'s',chatId:'c',role:'assistant',text:'Original synthetic opener.',ordinal:0}];await s.saveVaultAtomic(db,v);localStorage.setItem('vesper.ui.lastTab','story');localStorage.setItem('vesper.ui.lastStoryId','s');}""")
   await page.reload();await page.locator('.assistant-controls').wait_for();before=await page.evaluate(state)
   await page.click('[aria-label="Edit this reply"]');await page.fill('#assistantEditText','Canceled edit');await page.click('#assistantEditCancel');assert await page.evaluate(state)==before
   await page.click('[aria-label="Edit this reply"]');await page.fill('#assistantEditText',' ');await page.click('#assistantEditSave');assert 'empty' in await page.locator('#assistantEditError').inner_text();assert await page.evaluate(state)==before

   if device!='Desktop':await page.set_viewport_size({'width':opts['viewport']['width'],'height':420})
   await page.fill('#assistantEditText','Corrected synthetic opener.\n\nSecond paragraph.');await page.click('#assistantEditSave');await page.locator('#assistantEditPanel').wait_for(state='detached');after=await page.evaluate(state);assert after['messages'][0]['id']=='m';assert after['messages'][0]['ordinal']==0;assert after['messages'][0]['text']=='Corrected synthetic opener.\n\nSecond paragraph.'
   for k in before:
    if k not in ['messages','updatedAt']:assert after[k]==before[k],k
   await page.reload();await page.locator('.assistant-controls').wait_for();assert 'Corrected synthetic opener.' in await page.locator('.message').inner_text()
   checks=await page.evaluate("""async()=>{const st=await import('./src/storage/vault-store.js'),pa=await import('./src/prompt/prompt-assembler.js'),b=await import('./src/backup/vesper-backup.js'),im=await import('./src/migration/import-service.js'),turn=await import('./src/chat/turn-engine.js'),db=await st.openVesperDb(),v=await st.loadVault(db);const restored=im.prepareImport(b.parseVesperBackup(b.serializePortableBackup(v))).vault;const basePrompt=pa.assemblePrompt({vault:restored,storyId:'s',chatId:'c'});for(let i=1;i<=45;i++)restored.messages.push({id:'later-'+i,storyId:'s',chatId:'c',role:'user',ordinal:i,text:'Later unrelated turn.'});const oldPrompt=pa.assemblePrompt({vault:restored,storyId:'s',chatId:'c'}),other=pa.assemblePrompt({vault:restored,storyId:'s',chatId:'other-chat'});const saved=globalThis.fetch,bodies=[];globalThis.fetch=async(_url,options)=>{bodies.push(JSON.parse(options.body));return {ok:true,json:async()=>({choices:[{message:{content:bodies.length===1?'Amanda decided to leave.':'The room settled quietly.'}}]})};};try{localStorage.setItem('vesper.secret.openrouter-api-key','synthetic-key');await turn.runTurn({vault:restored,storyId:'s',chatId:'c',model:'synthetic'});}finally{globalThis.fetch=saved;localStorage.removeItem('vesper.secret.openrouter-api-key');}return {authority:basePrompt.authoritativeEdits.messages[0].text===v.messages[0].text,staleExcluded:!JSON.stringify(basePrompt).includes('STALE_BLUE_BOX'),unrelatedPreserved:JSON.stringify(basePrompt).includes('SAFE_UNRELATED_CANON'),outsideWindow:!oldPrompt.recentMessages.some(m=>m.id==='m')&&oldPrompt.authoritativeEdits.messages[0].text===v.messages[0].text,chatIsolated:!other.authoritativeEdits,providerRepair:bodies.length===2&&bodies.every(body=>body.messages[0].content.includes('Corrected synthetic opener.')&&!JSON.stringify(body).includes('STALE_BLUE_BOX')&&!JSON.stringify(body).includes('Original synthetic opener.'))};}""")
   assert all(checks.values()),checks;assert await page.evaluate(state)==after
   await page.click('[aria-label="Edit this reply"]');assert await page.locator('#assistantEditOriginal').count()==1;await page.click('#assistantEditOriginal');assert await page.locator('#assistantEditText').input_value()=='Original synthetic opener.';assert await page.evaluate(state)==after;await page.click('#assistantEditCancel')
   await page.click('[aria-label="Edit this reply"]');await page.fill('#assistantEditText','Stale edit');latest=await page.evaluate("""async()=>{const s=await import('./src/storage/vault-store.js'),db=await s.openVesperDb(),v=await s.loadVault(db);v.messages.push({id:'new',storyId:'s',chatId:'c',role:'user',text:'Newer synthetic data.',ordinal:1});await s.saveVaultAtomic(db,v);return s.loadVault(db);} """);await page.click('#assistantEditSave');await page.wait_for_function("document.querySelector('#assistantEditError').textContent.includes('vault changed')");assert await page.evaluate(state)==latest;await page.click('#assistantEditCancel')
   # A real IndexedDB abort must leave both message text and authority metadata unchanged.
   await page.reload();await page.locator('.assistant-controls').wait_for();abort_before=await page.evaluate(state);await page.click('[aria-label="Edit this reply"]');await page.fill('#assistantEditText','Interrupted synthetic correction.')
   await page.evaluate("""()=>{window.originalEditPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){const request=window.originalEditPut.call(this,value,key);if(key==='active')queueMicrotask(()=>this.transaction.abort());return request;};}""")
   await page.click('#assistantEditSave');await page.wait_for_function("document.querySelector('#assistantEditError').textContent.length>0");assert await page.evaluate(state)==abort_before;assert await page.locator('#assistantEditText').input_value()=='Interrupted synthetic correction.'
   await page.evaluate("()=>{IDBObjectStore.prototype.put=window.originalEditPut;}");await page.click('#assistantEditCancel')
   # Restore an edited synthetic backup through the real atomic replacement path.
   await page.evaluate("""async()=>{const st=await import('./src/storage/vault-store.js'),b=await import('./src/backup/vesper-backup.js'),im=await import('./src/migration/import-service.js'),db=await st.openVesperDb(),v=await st.loadVault(db),prepared=im.prepareImport(b.parseVesperBackup(b.serializePortableBackup(v)));await im.commitPreparedImport(db,prepared,{expectedRevision:v.storageRevision});}""")
   await page.reload();await page.locator('.assistant-controls').wait_for();restored=await page.evaluate(state)
   for key in ['messages','memoryEntries','milestones','relationships','stories','characters','personas']:assert restored[key]==abort_before[key],key
   restored_prompt=await page.evaluate("""async()=>{const st=await import('./src/storage/vault-store.js'),pa=await import('./src/prompt/prompt-assembler.js');return pa.assemblePrompt({vault:await st.loadVault(await st.openVesperDb()),storyId:'s',chatId:'c'});} """)
   assert restored_prompt['authoritativeEdits']['messages'][0]['text']=='Corrected synthetic opener.\n\nSecond paragraph.';assert 'STALE_BLUE_BOX' not in json.dumps(restored_prompt)
   assert not errors,errors;print(json.dumps({'device':device,'cancelAndEmptyUnchanged':True,'openerEdited':True,'identityAndDataPreserved':True,'reload':True,'staleConflictUnchanged':True,'realIndexedDB':True,'authorityChecks':checks,'originalRecovery':True,'transactionAbortUnchanged':True,'atomicBackupRestore':True,'errors':errors}),flush=True);await ctx.close()
  await browser.close()
asyncio.run(run());server.shutdown()
