import test from "node:test";
import assert from "node:assert/strict";
import {emptyVault} from "../src/schema.js";
import {findMilestoneCandidates} from "../src/stats/engine.js";
import {DEFAULT_MILESTONE_CANDIDATES} from "../src/stats/defaults.js";
import {assessMilestoneCandidate,confirmMilestone} from "../src/milestones/verifier.js";
import {buildStoryContext} from "../src/prompt/context-builder.js";
import {assemblePrompt} from "../src/prompt/prompt-assembler.js";
import {continuityPrompt} from "../src/continuity/guards.js";
import {setRelationshipStage} from "../src/relationships/relationship-state.js";
import {serializePortableBackup,parseVesperBackup} from "../src/backup/vesper-backup.js";
import {prepareImport} from "../src/migration/import-service.js";
import {runTurn} from "../src/chat/turn-engine.js";

function fixture(){
 const v=emptyVault();v.personas=[{id:'p',name:'Amanda'}];v.characters=[{id:'x',name:'Aedan'},{id:'y',name:'Aeron'},{id:'foreign',name:'Other Character'}];
 v.stories=[{id:'s',title:'Story',personaId:'p',characterIds:['x','y']},{id:'other',title:'Other',characterIds:['foreign']}];v.chats=[{id:'a',storyId:'s'},{id:'b',storyId:'s'},{id:'other-chat',storyId:'other'}];
 v.messages=[{id:'proof',storyId:'s',chatId:'a',role:'user',text:'Amanda and Aedan completed their mate bond.',ordinal:0,participantIds:['p','x']},{id:'foreign-proof',storyId:'other',chatId:'other-chat',role:'user',text:'Other Character completed a mate bond.',ordinal:0},{id:'b-proof',storyId:'s',chatId:'b',role:'user',text:'Amanda and Aedan completed their mate bond.',ordinal:0}];
 v.relationships=[{id:'r',storyId:'s',participantIds:['p','x'],stage:'friends'}];return v;
}
function canonical(v,patch={}){return {id:'m',storyId:'s',chatId:'a',type:'mated',participants:['p','x'],evidence:v.messages[0].text,sourceMessageId:'proof',status:'confirmed',...patch};}
function prompt(v,chatId='a'){return assemblePrompt({vault:v,storyId:'s',chatId});}
function noCanon(v){const p=prompt(v);assert.deepEqual(p.milestones,[]);assert.equal(p.mateBondCanon,null);assert.deepEqual(p.canonAndContinuity.confirmedMilestones,[]);return p;}

for(const status of ['candidate','detected','proposed','suggested','provisional','pending','inferred','rejected','disputed','retconned'])test(`${status} mated milestone cannot establish canon`,()=>{const v=fixture();v.milestones=[canonical(v,{status})];noCanon(v);assert.equal(v.milestones[0].status,status);});
test('status alone and empty evidence never establish a mate bond',()=>{const v=fixture();v.milestones=[canonical(v,{evidence:'',sourceMessageId:null})];noCanon(v);});
test('scanner false positives stay proposed and cannot be confirmed without verification',()=>{
 const v=fixture();v.messages[0].text='Amanda almost kissed him and imagined a mate bond completed.';
 const [candidate]=findMilestoneCandidates({message:v.messages[0],definitions:DEFAULT_MILESTONE_CANDIDATES});const assessed=assessMilestoneCandidate({...candidate,status:'confirmed'},v.messages[0].text);
 assert.equal(assessed.status,'candidate');assert.throws(()=>confirmMilestone(assessed,{storyId:'s',chatId:'a',participants:['p','x'],evidence:v.messages[0].text,vault:v}),/verification|evidence|completed/i);
});
for(const text of ['Amanda never completed their mate bond.','Amanda dreamed their mate bond completed.','Amanda suggested they might become mated.','The model predicts they will be mated.'])test(`non-event evidence is not canonical: ${text}`,()=>{const v=fixture();v.messages[0].text=text;v.milestones=[canonical(v)];noCanon(v);});
test('model output is not explicit canonical evidence without user verification',()=>{const v=fixture();v.messages[0].role='assistant';v.milestones=[canonical(v,{source:'model'})];noCanon(v);});
test('verified completed existing source-backed milestones keep working',()=>{const v=fixture();v.milestones=[canonical(v)];const p=prompt(v);assert.equal(p.milestones.length,1);assert.ok(p.mateBondCanon);assert.equal(p.canonAndContinuity.confirmedMilestones.length,1);});
test('explicit user-verified assistant evidence remains valid',()=>{const v=fixture();v.messages[0].role='assistant';v.milestones=[canonical(v,{verification:{verified:true,completed:true,verifiedBy:'user'}})];assert.ok(prompt(v).mateBondCanon);});
test('explicit user confirmation supports completed historical events without a source message',()=>{const v=fixture();v.milestones=[canonical(v,{sourceMessageId:null,verification:{verified:true,completed:true,verifiedBy:'user'}})];assert.ok(prompt(v).mateBondCanon);});
for(const patch of [{storyId:'other'},{chatId:'b'},{sourceMessageId:'foreign-proof'},{sourceMessageId:'b-proof'},{participants:['p','foreign']},{participants:['p','missing']},{participants:['x','x']},{verification:{verified:false,completed:true}},{verification:{verified:true,completed:false}},{evidence:'A fabricated quote.'}])test(`invalid ownership/completion/evidence rejected: ${JSON.stringify(patch)}`,()=>{const v=fixture();v.milestones=[canonical(v,patch)];noCanon(v);});
test('source participant identities must match the milestone participants',()=>{const v=fixture();v.milestones=[canonical(v,{participants:['p','y']})];noCanon(v);});
test('only the participants in a validated bond receive its relationship canon',()=>{const v=fixture();v.relationships[0].participantIds=['p','y'];v.milestones=[canonical(v)];assert.equal(prompt(v).mateBondCanon,null);});
test('verified story canon remains shared without changing its evidence ownership',()=>{const v=fixture();v.milestones=[canonical(v)];const p=prompt(v,'b');assert.equal(p.milestones.length,1);assert.ok(p.mateBondCanon);assert.equal(p.milestones[0].chatId,'a');});
test('explicitly chat-scoped milestones cannot affect another chat',()=>{const v=fixture();v.milestones=[canonical(v,{scope:'chat'})];const p=prompt(v,'b');assert.deepEqual(p.milestones,[]);assert.equal(p.mateBondCanon,null);});
test('duplicate canonical evidence counts once without rewriting history',()=>{const v=fixture();const m=canonical(v);v.milestones=[m,{...m,id:'duplicate',participants:['x','p']}];const before=structuredClone(v);assert.equal(prompt(v).milestones.length,1);assert.deepEqual(v,before);});
test('a contradictory milestone cannot replace or upgrade established canon',()=>{const v=fixture();v.milestones=[canonical(v),canonical(v,{id:'conflict',type:'married',contradictsMilestoneId:'m'})];const p=prompt(v);assert.deepEqual(p.milestones.map(m=>m.id),['m']);assert.equal(v.milestones.length,2);});
test('relationship stage cannot be upgraded from an unverified milestone',()=>{const v=fixture();v.milestones=[canonical(v,{status:'candidate'})];assert.throws(()=>setRelationshipStage(v.relationships[0],'mated',undefined,{vault:v,milestoneId:'m'}),/canonical|verified|milestone/i);assert.equal(v.relationships[0].stage,'friends');});
test('relationship upgrades validate type and participant ownership',()=>{const v=fixture();v.milestones=[canonical(v,{type:'first_kiss'})];assert.throws(()=>setRelationshipStage(v.relationships[0],'mated',undefined,{vault:v,milestoneId:'m'}),/milestone|stage/i);});
test('a valid milestone can explicitly upgrade its own relationship',()=>{const v=fixture();v.milestones=[canonical(v)];assert.equal(setRelationshipStage(v.relationships[0],'mated',undefined,{vault:v,milestoneId:'m'}).stage,'mated');});
test('relationship canon upgrade cannot omit evidence validation',()=>{const v=fixture();assert.throws(()=>setRelationshipStage(v.relationships[0],'mated'),/verified|evidence|milestone/i);});
test('new confirmation requires explicit verification and prevents duplicate promotion',()=>{const v=fixture();const candidate={key:'mated',sourceMessageId:'proof'};const options={storyId:'s',chatId:'a',participants:['p','x'],evidence:v.messages[0].text,vault:v,verification:{verified:true,completed:true,verifiedBy:'user'}};const m=confirmMilestone(candidate,options);assert.equal(m.status,'confirmed');v.milestones.push(m);assert.throws(()=>confirmMilestone(candidate,options),/already canonical/);});
test('contradictory confirmation cannot discard candidate conflict provenance',()=>{const v=fixture();v.milestones=[canonical(v)];assert.throws(()=>confirmMilestone({key:'mated',sourceMessageId:'proof',contradictsMilestoneId:'m'},{storyId:'s',chatId:'a',participants:['p','x'],evidence:v.messages[0].text,vault:v,verification:{verified:true,completed:true,verifiedBy:'user'}}),/Contradictory/);});
test('nested established facts cannot launder provisional milestone references',()=>{const v=fixture();v.milestones=[canonical(v,{status:'candidate'})];v.relationships[0].establishedFacts=[{id:'fact',text:'UNVERIFIED-NESTED-CANON',status:'confirmed',sourceMilestoneId:'m'}];assert.ok(!JSON.stringify(noCanon(v)).includes('UNVERIFIED-NESTED-CANON'));});
test('stored milestone-derived relationships and canon cannot bypass validation',()=>{const v=fixture();v.milestones=[canonical(v,{status:'provisional'})];v.relationships[0]={...v.relationships[0],stage:'mated',sourceMilestoneId:'m'};v.memoryEntries=[{id:'derived',storyId:'s',chatId:'a',kind:'canon',status:'active',text:'UNVERIFIED-DERIVED-CANON',sourceMilestoneId:'m'}];const p=noCanon(v);assert.equal(p.relationship,null);assert.ok(!JSON.stringify(p).includes('UNVERIFIED-DERIVED-CANON'));assert.equal(v.memoryEntries.length,1);});
test('summary references do not upgrade milestones or relationship state',()=>{const v=fixture();v.milestones=[canonical(v,{status:'candidate'})];v.memoryEntries=[{id:'summary',storyId:'s',chatId:'a',kind:'summary',status:'active',text:'A summary suggests the bond is completed.',sourceMilestoneIds:['m']}];assert.ok(!JSON.stringify(noCanon(v)).includes('A summary suggests'));});
test('standalone continuity cannot trust a confirmed label without vault evidence',()=>{assert.deepEqual(continuityPrompt({milestones:[{status:'confirmed',type:'mated'}]}).confirmedMilestones,[]);});
test('evidence validation survives reload and backup/restore while history stays intact',()=>{const v=fixture();v.milestones=[canonical(v),canonical(v,{id:'pending',type:'married',status:'provisional'})];const restored=prepareImport(parseVesperBackup(serializePortableBackup(v))).vault;const p=prompt(JSON.parse(JSON.stringify(restored)));assert.deepEqual(p.milestones.map(m=>m.id),['m']);assert.equal(restored.milestones.length,2);assert.deepEqual(restored.milestones,v.milestones);});
test('provider and repair payloads omit provisional canonical claims',async()=>{const v=fixture();v.messages=[];v.milestones=[canonical(fixture(),{status:'provisional'})];const bodies=[],oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage;globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_u,o)=>{bodies.push(JSON.parse(o.body));return {ok:true,json:async()=>({choices:[{message:{content:bodies.length===1?'Mandy.':'The candle flickered.'}}]})};};try{await runTurn({vault:v,storyId:'s',chatId:'a',model:'synthetic-model'});assert.equal(bodies.length,2);for(const b of bodies){assert.ok(!JSON.stringify(b).includes('MATE BOND — ESTABLISHED'));const system=JSON.parse(b.messages[0].content);assert.deepEqual(system.milestones,[]);}}finally{globalThis.fetch=oldFetch;if(oldStorage===undefined)delete globalThis.localStorage;else globalThis.localStorage=oldStorage;}});
test('ambiguous duplicate milestone IDs cannot launder provisional provenance',()=>{const v=fixture();v.milestones=[canonical(v),canonical(v,{status:'candidate'})];noCanon(v);});
test('provisional or model-inferred relationship stages do not bypass milestone validation',()=>{for(const patch of [{status:'provisional'},{source:'model'},{source:'scanner'},{inferred:true}]){const v=fixture();v.relationships[0]={...v.relationships[0],stage:'mated',...patch};assert.equal(prompt(v).mateBondCanon,null);}});
test('valid milestone canon still works without a structured relationship row',()=>{const v=fixture();v.relationships=[];v.milestones=[canonical(v)];assert.deepEqual(prompt(v).mateBondCanon.participantIds,['p','x']);});
test('imported confirmed labels cannot overwrite their provisional legacy status',()=>{const v=fixture();v.milestones=[canonical(v,{status:'confirmed-imported',legacy:{status:'provisional'}})];noCanon(v);});
test('standalone continuity deduplicates validated events',()=>{const v=fixture();const m=canonical(v);v.milestones=[m];assert.equal(continuityPrompt({vault:v,storyId:'s',chatId:'a',milestones:[m,m]}).confirmedMilestones.length,1);});
test('standalone continuity cannot accept milestone-derived canon without validated evidence',()=>{const v=fixture();v.milestones=[canonical(v,{status:'candidate'})];const c=continuityPrompt({vault:v,storyId:'s',chatId:'a',relationship:{stage:'mated',sourceMilestoneId:'m'},facts:[{status:'confirmed',text:'UNVERIFIED',sourceMilestoneId:'m'}],knowledge:[{sourceMilestoneId:'m'}]});assert.equal(c.relationship,null);assert.deepEqual(c.confirmedFacts,[]);assert.deepEqual(c.knowledge,[]);});
test('repair validation refreshes canon after milestone evidence is invalidated during a turn',async()=>{const v=fixture();v.milestones=[canonical(v)];const bodies=[],oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage;globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_u,o)=>{bodies.push(JSON.parse(o.body));if(bodies.length===1){v.milestones[0].status='provisional';return {ok:true,json:async()=>({choices:[{message:{content:'Mandy.'}}]})};}return {ok:true,json:async()=>({choices:[{message:{content:'Are we together?'}}]})};};try{const result=await runTurn({vault:v,storyId:'s',chatId:'a',model:'synthetic-model'});assert.equal(bodies.length,2);assert.equal(result.blocked,false);assert.equal(JSON.parse(bodies[1].messages[0].content).mateBondCanon,null);}finally{globalThis.fetch=oldFetch;if(oldStorage===undefined)delete globalThis.localStorage;else globalThis.localStorage=oldStorage;}});
for(const text of ['Amanda and Aedan planned their first kiss.','Amanda and Aedan discussed their first kiss.','Amanda and Aedan hope for their first kiss.'])test(`a first-kiss mention is not completed evidence: ${text}`,()=>{const v=fixture();v.messages[0].text=text;v.milestones=[canonical(v,{type:'first_kiss'})];noCanon(v);});
test('an explicitly narrated completed first kiss remains canonical',()=>{const v=fixture();v.messages[0].text='Amanda and Aedan shared their first kiss.';v.milestones=[canonical(v,{type:'first_kiss'})];assert.equal(prompt(v).milestones.length,1);});
