import test from 'node:test';
import assert from 'node:assert/strict';
import {createMilestoneNotifications} from '../src/ui/milestone-notifications.js';
import {emptyVault} from '../src/schema.js';
function fixture(){const v=emptyVault();v.personas=[{id:'p',name:'Persona'}];v.characters=[{id:'x',name:'Character'}];v.stories=[{id:'s',personaId:'p',characterIds:['x']}];v.chats=[{id:'c',storyId:'s'}];return v;}
function milestone(patch={}){return {id:'m',storyId:'s',chatId:'c',type:'first_kiss',title:'First kiss',participants:['p','x'],evidence:'They kissed.',status:'confirmed',verification:{verified:true,completed:true,verifiedBy:'user'},...patch};}
function setup(v=fixture()){const shown=[];let dismiss;const n=createMilestoneNotifications({show:(m,close)=>{shown.push(m.id);dismiss=close;},hide:()=>{}});n.baseline(v);return {v,n,shown,close:()=>dismiss()};}
test('new verified completion displays exactly once; dismissal advances queue',()=>{const {v,n,shown,close}=setup();v.milestones=[milestone(),milestone({id:'n',type:'first_date',evidence:'They had a date.'})];n.observe(v);assert.deepEqual(shown,['m']);n.observe(v);close();assert.deepEqual(shown,['m','n']);close();n.observe(v);assert.deepEqual(shown,['m','n']);});
for(const patch of [{status:'candidate'},{status:'rejected'},{provisional:true},{contradictsMilestoneId:'other'},{storyId:'wrong'},{chatId:'wrong'},{participants:['foreign']},{verification:{verified:false}},{evidence:'They almost kissed.'}])test(`invalid milestone has no notification: ${JSON.stringify(patch)}`,()=>{const {v,n,shown}=setup();v.milestones=[milestone(patch)];n.observe(v);assert.deepEqual(shown,[]);});
test('candidate becomes verified once, ordinary updates do not replay',()=>{const v=fixture();v.milestones=[milestone({status:'candidate'})];const {n,shown,close}=setup(v);v.milestones[0].status='confirmed';n.observe(v);close();v.milestones[0].updatedAt='later';n.observe(v);assert.deepEqual(shown,['m']);});
test('duplicate event with another ID cannot replay after deletion or repair',()=>{const {v,n,shown,close}=setup();v.milestones=[milestone()];n.observe(v);close();v.milestones=[];n.observe(v);v.milestones=[milestone({id:'copy'})];n.observe(v);assert.deepEqual(shown,['m']);});
test('reload and restore baseline historical canon without replay',()=>{const v=fixture();v.milestones=[milestone()];const {n,shown}=setup(v);n.observe(v);n.baseline(structuredClone(v));n.observe(v);assert.deepEqual(shown,[]);});
test('transitions and rerenders do not remove active popup or lose queue',()=>{const {v,n,shown,close}=setup();v.milestones=[milestone()];n.observe(v);n.observe(structuredClone(v));assert.deepEqual(shown,['m']);close();n.observe(v);assert.deepEqual(shown,['m']);});
test('queued invalidated evidence is never rendered',()=>{const {v,n,shown,close}=setup();v.milestones=[milestone(),milestone({id:'n',type:'first_date',evidence:'They had a date.'})];n.observe(v);v.milestones[1].status='rejected';n.observe(v);close();assert.deepEqual(shown,['m']);});
test('explicit new verification revision can notify again',()=>{const {v,n,shown,close}=setup();v.milestones=[milestone()];n.observe(v);close();v.milestones[0].status='rejected';n.observe(v);v.milestones[0].status='confirmed';v.milestones[0].verification.verifiedAt='new verification';n.observe(v);assert.deepEqual(shown,['m','m']);});
test('repairing verification metadata on already canonical event does not replay',()=>{const {v,n,shown,close}=setup();v.milestones=[milestone()];n.observe(v);close();v.milestones[0].verification.verifiedAt='metadata refresh';n.observe(v);assert.deepEqual(shown,['m']);});

import {saveVaultAtomic,replaceVaultAtomic,subscribeVaultSaves} from '../src/storage/vault-store.js';
import {vaultDb} from '../test-support/vault-db.js';
import {loadVault} from '../src/storage/vault-store.js';
function fakeDb(fail=false){return vaultDb({failWrites:fail});}
test('notification observes only a successful commit and cannot mutate the saved value',async()=>{const db=fakeDb(),v=await loadVault(db);Object.assign(v,fixture());let calls=0;const off=subscribeVaultSaves(event=>{assert.ok(db.records.has("active"));calls++;event.vault.stories=[];throw new Error('UI failure');});try{const saved=await saveVaultAtomic(db,v);assert.equal(calls,1);assert.equal(saved.stories.length,1);assert.equal(v.stories.length,1);}finally{off();}});
test('aborted save emits no completion notification',async()=>{let calls=0;const off=subscribeVaultSaves(()=>calls++);try{const db=fakeDb(true),v=await loadVault(db);await assert.rejects(saveVaultAtomic(db,v),/aborted/);assert.equal(calls,0);}finally{off();}});
test('restore commits deliver a historical baseline signal, not a new completion',async()=>{const events=[],off=subscribeVaultSaves(event=>events.push(event.kind));try{await replaceVaultAtomic(fakeDb(),fixture());assert.deepEqual(events,['replace']);}finally{off();}});
test('duplicate copy with a different verification timestamp cannot masquerade as re-verification',()=>{const {v,n,shown,close}=setup();v.milestones=[milestone()];n.observe(v);close();v.milestones=[];n.observe(v);v.milestones=[milestone({id:'copy',verification:{verified:true,completed:true,verifiedBy:'user',verifiedAt:'later'}})];n.observe(v);assert.deepEqual(shown,['m']);});
