import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyVault} from '../src/schema.js';
import {runTurn} from '../src/chat/turn-engine.js';
import {prepareAssistantEdit} from '../src/chat/message-edit.js';
function fixture(){const v=emptyVault();v.personas=[{id:'p',name:'Player'}];v.characters=[{id:'c',name:'Character'}];v.stories=[{id:'s',personaId:'p',characterIds:['c'],premise:'An initial disagreement.'}];v.chats=[{id:'a',storyId:'s'},{id:'b',storyId:'s'}];v.messages=[{id:'decision',storyId:'s',chatId:'a',role:'user',text:'I enjoyed that. We resolved the disagreement and chose to be together.',ordinal:0}];for(let i=1;i<46;i++)v.messages.push({id:`m${i}`,storyId:'s',chatId:'a',role:'assistant',text:'The afternoon continued.',ordinal:i});return v;}
async function capture(v,options={}){const calls=[],fetch=globalThis.fetch,storage=globalThis.localStorage;globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_,o)=>{calls.push(JSON.parse(o.body));return {ok:true,json:async()=>({choices:[{message:{content:options.repair&&calls.length===1?'':'A quiet moment.'}}]})};};try{await runTurn({vault:v,storyId:'s',chatId:'a',model:'synthetic',personaDraft:true,...options});return calls;}finally{globalThis.fetch=fetch;if(storage===undefined)delete globalThis.localStorage;else globalThis.localStorage=storage;}}
test('My Turn preserves older player decisions and explicit continuity precedence without changing vault',async()=>{const v=fixture(),before=structuredClone(v),calls=await capture(v);const content=calls[0].messages.map(m=>m.content).join('\n');assert.match(content,/We resolved the disagreement/);assert.match(content,/later explicit player/);assert.match(content,/Never invent regret/);assert.match(content,/editable draft/);assert.deepEqual(v,before);});
test('My Turn history cannot cross chat or persona ownership',async()=>{const v=fixture();v.messages.push({id:'foreign',storyId:'s',chatId:'b',role:'user',text:'OTHER_CHAT_SECRET',ordinal:47},{id:'draft',storyId:'s',chatId:'a',role:'user',status:'draft',text:'UNSENT_SECRET',ordinal:-1});v.personas.push({id:'q',name:'New Player'});v.stories[0].personaBinding={personaId:'q',history:[]};const content=JSON.stringify(await capture(v));assert.ok(!content.includes('We resolved the disagreement'));assert.ok(!content.includes('OTHER_CHAT_SECRET'));assert.ok(!content.includes('UNSENT_SECRET'));});
test('ordinary provider and repair retain authoritative edits after reload',async()=>{let v=fixture();v=prepareAssistantEdit(v,{messageId:'m1',storyId:'s',chatId:'a',text:'CORRECTED: They resolved the misunderstanding.',now:'2026-01-01T00:00:00Z'});v=JSON.parse(JSON.stringify(v));const calls=await capture(v,{repair:true,personaDraft:false});assert.equal(calls.length,2);for(const call of calls){assert.match(JSON.stringify(call),/CORRECTED/);}});
test('current player objections remain evidence; consent protections are explicit',async()=>{const v=fixture();v.messages.push({id:'new-boundary',storyId:'s',chatId:'a',role:'user',text:'I changed my mind. Please stop.',ordinal:46});const content=JSON.stringify(await capture(v));assert.match(content,/I changed my mind/);assert.match(content,/Past consent is not blanket future consent/);assert.match(content,/all hard limits/);});
test('excluded player records never enter supplemental history',async()=>{const v=fixture();v.messages[0].status='forgotten';const content=JSON.stringify(await capture(v));assert.ok(!content.includes('We resolved the disagreement'));});
test('ordinary AI turns do not receive My Turn supplemental context',async()=>{const calls=await capture(fixture(),{personaDraft:false});assert.ok(!JSON.stringify(calls).includes('SOURCE-BACKED PLAYER HISTORY'));});

test('affectionate progression outranks opening conflict in My Turn source context',async()=>{const v=fixture();v.stories[0].openingScene='The character regrets an earlier privacy violation.';v.messages.push({id:'affection',storyId:'s',chatId:'a',role:'user',text:'I accept your feelings and want this relationship.',ordinal:46});const call=(await capture(v))[0];const context=JSON.parse(call.messages[0].content);assert.equal(context.storyPremise,undefined);assert.equal(context.openingScene,undefined);assert.equal(context.historicalSetup.openingScene,v.stories[0].openingScene);assert.match(JSON.stringify(call),/I accept your feelings/);assert.match(JSON.stringify(call),/not an unresolved obligation/);});
test('future confrontation cannot be inferred solely from the original premise',async()=>{const v=fixture(),call=(await capture(v))[0];const content=JSON.stringify(call);assert.match(content,/Do not schedule a future confrontation/);assert.match(content,/Never assume forgiveness/);assert.match(content,/genuinely unresolved concerns/);});
test('invalid My Turn draft does not automatically request a paid repair',async()=>{const calls=await capture(fixture(),{repair:true});assert.equal(calls.length,1);});

test('My Turn keeps authoritative correction outside recent history after reload',async()=>{let v=fixture();v=prepareAssistantEdit(v,{messageId:'m1',storyId:'s',chatId:'a',text:'CORRECTED: The player established that the earlier disagreement was resolved.',now:'2026-01-01T00:00:00Z'});const call=(await capture(JSON.parse(JSON.stringify(v))))[0];assert.match(JSON.stringify(call),/CORRECTED/);assert.match(JSON.stringify(call),/We resolved the disagreement/);assert.match(JSON.stringify(call),/Authoritative message edits replace superseded versions/);});
