import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {emptyVault} from '../src/schema.js';
import {sha256,canonicalJSON,verifyEventProof,eventSourceCurrent} from '../src/phone/phone-event-evidence.js';
import {previewPhoneEvents,applyPhoneEvents,commitPhoneEvents} from '../src/phone/phone-event-import.js';
import {vaultDb} from '../test-support/vault-db.js';
import {loadVault,saveVaultAtomic} from '../src/storage/vault-store.js';
for(const value of ['', 'abc', '🙂 café', 'x'.repeat(1000)])test('event digest matches SHA-256: '+value.length,()=>assert.equal(sha256(value),createHash('sha256').update(value).digest('hex')));
test('canonical evidence digest ignores object key order, preserves array order',()=>{assert.equal(canonicalJSON({b:2,a:1}),canonicalJSON({a:1,b:2}));assert.notEqual(canonicalJSON([1,2]),canonicalJSON([2,1]));});
test('unknown or forged approval roots never authorize an event',()=>{assert.equal(verifyEventProof({claim:{},root:'0'.repeat(64),proof:[]}),false);assert.equal(verifyEventProof(null),false);});
test('missing recovery evidence cannot become model-visible',()=>assert.equal(eventSourceCurrent({recovery:{version:3},text:'Synthetic'},emptyVault()),false));
test('an unknown ledger is excluded without changing its source vault',()=>{const v=emptyVault(),before=structuredClone(v);const p=previewPhoneEvents(v,{version:1,entries:[{claim:{eventId:'synthetic'},root:'0'.repeat(64),proof:[]}]});assert.equal(p.accepted.length,0);assert.equal(p.excluded.length,1);assert.deepEqual(v,before);});
test('confirmation is required even for an empty import',()=>assert.throws(()=>applyPhoneEvents(emptyVault(),{},{}),/confirm/i));
test('preview revision conflict fails without modifying the database',async()=>{const db=vaultDb(),a=await loadVault(db);await saveVaultAtomic(db,a);const p=previewPhoneEvents(a,{version:1,entries:[]});const b=await loadVault(db);await saveVaultAtomic(db,b);const before=await loadVault(db);await assert.rejects(commitPhoneEvents(db,a,p,{confirmed:true}),e=>e.code==='VESPER_VAULT_CONFLICT');assert.deepEqual(await loadVault(db),before);});
// The approved corpus stays outside the repository because it contains private
// history. Supply the local verified package and backup for acceptance tests.
const fixtureDir=process.env.VESPER_PHONE_EVENT_FIXTURE_DIR;
const corpusOptions={skip:!fixtureDir};
async function corpus(){
 const {readFile}=await import('node:fs/promises');
 const paths=JSON.parse(await readFile(fixtureDir+'/source-hashes.json','utf8'));
 const backupPath=Object.keys(paths).find(p=>p.endsWith('.json'));
 return {vault:JSON.parse(await readFile(backupPath,'utf8')),packageData:JSON.parse(await readFile(fixtureDir+'/verified-package.private.json','utf8'))};
}
let corpusCache;
async function imported(){
 corpusCache??=(async()=>{const {vault,packageData}=await corpus();const preview=previewPhoneEvents(vault,packageData,'2026-10-08T12:00:00.000Z');const next=applyPhoneEvents(vault,preview,{confirmed:true});return {vault,packageData,preview,next};})();
 return structuredClone(await corpusCache);
}
test('approved ledger imports all 1462 events into eight correctly owned threads',corpusOptions,async()=>{const {preview,next}=await imported();assert.equal(preview.accepted.length,1462);assert.deepEqual(preview.excluded,[]);const story=next.stories.find(s=>s.id===preview.accepted[0].claim.event.storyId);assert.equal(story.phone.threads.length,8);assert.equal(story.phone.threads.flatMap(t=>t.messages).length,1462);});
test('all 76 Lucien events remain private, never redirected to group',corpusOptions,async()=>{const {next}=await imported();const threads=next.stories.flatMap(s=>s.phone?.threads||[]);const lucien=threads.find(t=>t.kind==='private'&&t.participantIds.includes('character_210ff3ee-5474-4f85-aa2d-20e1e604202e'));assert.equal(lucien.messages.length,76);assert(lucien.messages.every(m=>m.audienceIds.length===2));});
test('repeat imports add zero events and preserve separate legitimate repeats',corpusOptions,async()=>{const {next,packageData}=await imported();const p=previewPhoneEvents(next,packageData);assert.equal(p.accepted.length,0);assert.equal(p.duplicates.length,1462);assert.deepEqual(applyPhoneEvents(next,p,{confirmed:true}),next);const msgs=next.stories.flatMap(s=>s.phone?.threads||[]).flatMap(t=>t.messages);const displayed=packageData.entries.find(e=>e.claim.event.sourceOrdinal===79&&e.claim.event.representations.length>1);assert(displayed,'linked displays must exist');assert.equal(msgs.filter(m=>m.recovery.key===displayed.claim.event.id).length,1);const repeats=new Map();for(const entry of packageData.entries){const c=entry.claim,e=c.event,key=canonicalJSON([e.conversationId,e.sourceOrdinal,c.senderId,c.audienceIds,e.text]);if(!repeats.has(key))repeats.set(key,[]);repeats.get(key).push(e.id);}const separate=[...repeats.values()].filter(ids=>ids.length>1);assert(separate.length,'genuine repeated sends must exist');for(const ids of separate)assert.equal(msgs.filter(m=>ids.includes(m.recovery.key)).length,ids.length);});
test('original story records, unrelated stories and narration remain byte-equivalent',corpusOptions,async()=>{const {vault,next,preview}=await imported();const id=preview.accepted[0].claim.event.storyId;const a=structuredClone(vault),b=structuredClone(next);delete a.stories.find(s=>s.id===id).phone;delete b.stories.find(s=>s.id===id).phone;assert.deepEqual(a,b);});
for(const field of ['audienceIds','senderId','event','pdf','historicalSystemEvents'])test('tampered approved event '+field+' is rejected before writes',corpusOptions,async()=>{const {vault,packageData}=await corpus();const entry=structuredClone(packageData.entries[0]);entry.claim[field]=field==='audienceIds'?[]:field==='senderId'?'other':{};const p=previewPhoneEvents(vault,{version:1,entries:[entry]});assert.equal(p.accepted.length,0);assert.equal(p.excluded.length,1);});
test('changed source text and wrong-chat source invalidate approval evidence',corpusOptions,async()=>{const {vault,packageData}=await corpus();const e=packageData.entries[0],id=e.claim.sourceChecks[0].id;for(const mode of ['text','chatId']){const v=structuredClone(vault),source=v.messages.find(m=>m.id===id);if(mode==='text')source.text+=' changed';else source.chatId=v.chats.find(c=>c.storyId!==source.storyId).id;try{assert.equal(previewPhoneEvents(v,{version:1,entries:[e]}).accepted.length,0);}catch(err){assert.match(err.message,/Invalid|invalid|Phone|Vesper/);}}});
test('native backup round trip retains event proof, PDF provenance and membership',corpusOptions,async()=>{const {next}=await imported();const {buildPortableBackup,parseVesperBackup}=await import('../src/backup/vesper-backup.js');const restored=parseVesperBackup(JSON.stringify(buildPortableBackup(next)));assert.deepEqual(restored.stories,next.stories);});
test('corrupt persisted event cannot export or become model-visible',corpusOptions,async()=>{const {next}=await imported();const {buildPortableBackup}=await import('../src/backup/vesper-backup.js');const m=next.stories.flatMap(s=>s.phone?.threads||[]).flatMap(t=>t.messages)[0];m.audienceIds=[];assert.equal(eventSourceCurrent(m,next),false);assert.throws(()=>buildPortableBackup(next),/Invalid/);});
test('group leave/reentry audiences and private knowledge remain enforced',corpusOptions,async()=>{const {next}=await imported();const {phoneMessageVisible}=await import('../src/phone/phone-context.js');const ms=next.stories.flatMap(s=>s.phone?.threads||[]).flatMap(t=>t.messages);const dane='character_2773068d-0acf-436a-97ba-5f982810d648';const systems=ms.find(m=>m.recovery.sourceOrdinal===80).recovery.claim.historicalSystemEvents,leave=systems.find(e=>e.type==='leave'&&e.sourceOrdinal===80),rejoin=systems.find(e=>e.type==='join'&&e.sourceMessageId===leave.sourceMessageId&&e.start>leave.end);assert(leave&&rejoin);const absence=ms.filter(m=>m.recovery.claim.kind==='group'&&m.recovery.sourceMessageId===leave.sourceMessageId&&m.recovery.start>=leave.end&&m.recovery.start<rejoin.start);assert.equal(absence.length,2);assert(absence.every(m=>!phoneMessageVisible(next,m,[dane])));const privateMessage=ms.find(m=>m.recovery.claim.kind==='private'&&m.recovery.claim.participantIds[0]!==dane);assert.equal(phoneMessageVisible(next,privateMessage,[dane]),false);});
test('forgotten source is withheld, restoration restores only its original audience',corpusOptions,async()=>{const {next}=await imported();const m=next.stories.flatMap(s=>s.phone?.threads||[]).flatMap(t=>t.messages)[0],source=next.messages.find(s=>s.id===m.sourceMessageIds[0]);source.status='forgotten';assert.equal(eventSourceCurrent(m,next),false);assert.equal(eventSourceCurrent(m,next,{includeExcluded:true}),true);source.status='active';assert.equal(eventSourceCurrent(m,next),true);});
test('existing live messages, nicknames and current group membership stay intact',corpusOptions,async()=>{const {vault,packageData}=await corpus();const {ensureStoryPhone,appendPhoneMessage,setContactDisplayName,updatePhoneThread}=await import('../src/phone/phone-state.js');const s=vault.stories.find(s=>s.id===packageData.entries[0].claim.event.storyId),chatId=packageData.entries[0].claim.event.chatId;let v=ensureStoryPhone(vault,s.id,chatId);const t=v.stories.find(x=>x.id===s.id).phone.threads[0];v=appendPhoneMessage(v,s.id,t.id,{id:'synthetic-live',senderId:s.personaId,senderType:'persona',text:'Synthetic existing message.'});v=setContactDisplayName(v,s.id,t.participantIds[0],'Synthetic nickname');v=updatePhoneThread(v,s.id,t.id,{title:'Custom existing group',participantIds:t.participantIds.slice(0,2)});const before=structuredClone(v.stories.find(x=>x.id===s.id).phone.threads[0]);const n=applyPhoneEvents(v,previewPhoneEvents(v,packageData),{confirmed:true});assert.deepEqual(n.stories.find(x=>x.id===s.id).phone.threads.find(x=>x.id===t.id),before);assert.equal(n.stories.find(x=>x.id===s.id).phone.contactDisplayNames[t.participantIds[0]],'Synthetic nickname');});
test('legacy recovered representations suppress only the same source event',corpusOptions,async()=>{
 const {vault,packageData}=await corpus();const {scanPhoneHistory,applyPhoneHistory}=await import('../src/phone/phone-history.js');const {historyIdentities}=await import('../src/phone/phone-history-contacts.js');const storyId=packageData.entries[0].claim.event.storyId;
 const preview=scanPhoneHistory(vault,storyId),names=historyIdentities(vault,storyId);let native;
 for(const candidate of preview.candidates){
  const event=packageData.entries.find(e=>e.claim.kind==='group'&&e.claim.event.representations.some(r=>r.sourceMessageId===candidate.sourceMessageId&&r.start===candidate.start&&r.end===candidate.end&&e.claim.event.text===candidate.text));if(!event||candidate.kind!=='group')continue;
  const identities=Object.fromEntries(Object.keys(candidate.identities).map(label=>[label,names.find(n=>n.name.toLowerCase()===label.toLowerCase()||n.name.split(' ')[0].toLowerCase()===label.toLowerCase())?.id]));
  try{native=applyPhoneHistory(vault,preview,{confirmed:true,selectedKeys:[candidate.key],resolutions:{[candidate.key]:{confirmed:true,distinct:true,membershipConfirmed:true,identities,targetThreadId:vault.stories.find(s=>s.id===storyId).phone.threads[0].id}}});break;}catch{}
 }
 assert(native,'at least one exact native recovered representation must be available');
 const p=previewPhoneEvents(native,packageData);assert.equal(p.accepted.length,1461);assert.equal(p.duplicates.length,1);
 const n=applyPhoneEvents(native,p,{confirmed:true});assert.equal(n.stories.find(s=>s.id===storyId).phone.threads.flatMap(t=>t.messages).length,1462);
});
test('atomic import requires a verified checkpoint, supports rollback and rejects stale saves',corpusOptions,async()=>{const {vault,packageData}=await corpus();const db=vaultDb();await saveVaultAtomic(db,vault,{expectedRevision:(await loadVault(db)).storageRevision});const base=await loadVault(db),p=previewPhoneEvents(base,packageData);let checkpoint;
await assert.rejects(commitPhoneEvents(db,base,p,{confirmed:true}),/backup/);assert.deepEqual(await loadVault(db),base);
const saved=await commitPhoneEvents(db,base,p,{confirmed:true,onCheckpoint:value=>{checkpoint=value;}});assert(checkpoint.text);const {parseVesperBackup}=await import('../src/backup/vesper-backup.js');const backup=parseVesperBackup(checkpoint.text);assert.equal(sha256(checkpoint.text),checkpoint.sha256);await assert.rejects(saveVaultAtomic(db,base),e=>e.code==='VESPER_VAULT_CONFLICT');const {replaceVaultAtomic}=await import('../src/storage/vault-store.js');await replaceVaultAtomic(db,backup,{expectedRevision:saved.storageRevision});const restored=await loadVault(db);assert.deepEqual(restored.stories,base.stories);
});
test('checkpoint failure and aborted transaction preserve the original branch',corpusOptions,async()=>{const {vault,packageData}=await corpus();for(const abort of [false,true]){const db=vaultDb();await saveVaultAtomic(db,vault,{expectedRevision:(await loadVault(db)).storageRevision});const base=await loadVault(db),p=previewPhoneEvents(base,packageData);if(!abort){await assert.rejects(commitPhoneEvents(db,base,p,{confirmed:true,onCheckpoint:()=>{throw new Error('checkpoint failed');}}),/checkpoint failed/);assert.deepEqual(await loadVault(db),base);}else{const failDb=vaultDb({failWrites:true});failDb.records.set('active',structuredClone(base));failDb.records.set('revision',base.storageRevision);await assert.rejects(commitPhoneEvents(failDb,base,p,{confirmed:true,onCheckpoint:()=>{}}),/aborted/);assert.deepEqual(await loadVault(failDb),base);}}});
test('every reconstructed event respects the frozen audience in actual provider retrieval',corpusOptions,async()=>{const {next}=await imported();const {phoneMessageVisible,buildPhoneContext}=await import('../src/phone/phone-context.js');const story=next.stories.find(s=>s.phone?.threads.some(t=>t.messages.some(m=>m.recovery?.version===3)));const ids=[...story.characterIds,...story.phone.historicalContacts.map(c=>c.id)];let checked=0;for(const t of story.phone.threads)for(const m of t.messages)for(const id of ids){assert.equal(phoneMessageVisible(next,m,[id]),m.audienceIds.includes(id));checked++;}assert.equal(checked,10234);assert.deepEqual(buildPhoneContext(next,{storyId:story.id,chatId:next.chats.find(c=>c.storyId!==story.id).id,respondingCharacterIds:story.characterIds}),[]);});
test('regeneration cleanup removes event dependencies whose source branch was discarded',corpusOptions,async()=>{const {next}=await imported();const {reconcilePhoneDependencies}=await import('../src/phone/phone-context.js');const thread=next.stories.flatMap(s=>s.phone?.threads||[]).find(t=>t.kind==='private'&&t.participantIds.includes('character_210ff3ee-5474-4f85-aa2d-20e1e604202e')),discard=thread.messages[0].sourceMessageIds[0],removed=thread.messages.filter(m=>m.sourceMessageIds.includes(discard)).map(m=>m.id);next.messages=next.messages.filter(m=>m.id!==discard);const clean=reconcilePhoneDependencies(next);assert(removed.every(id=>!clean.stories.flatMap(s=>s.phone?.threads||[]).flatMap(t=>t.messages).some(m=>m.id===id)));const {validateVesperBackup}=await import('../src/backup/backup-validation.js');assert.equal(validateVesperBackup(clean).ok,true);});
test('ordinary Sync cannot re-import representations of verified historical events',corpusOptions,async()=>{const {next}=await imported();const {scanPhoneHistory}=await import('../src/phone/phone-history.js');const story=next.stories.find(s=>s.phone?.threads.some(t=>t.messages.some(m=>m.recovery?.version===3)));const spans=story.phone.threads.flatMap(t=>t.messages).flatMap(m=>m.recovery.claim.event.representations);const preview=scanPhoneHistory(next,story.id);assert(preview.duplicateCount>0);assert(!preview.candidates.some(c=>spans.some(r=>r.sourceMessageId===c.sourceMessageId&&r.chatId===c.chatId&&c.start<r.end&&c.end>r.start)));});
test('existing archival contact casing and nicknames are preserved without rejecting its identity',corpusOptions,async()=>{const {vault,packageData}=await corpus();const contacts=[...new Map(packageData.entries.flatMap(e=>e.claim.contacts).map(c=>[c.id,c])).values()];const story=vault.stories.find(s=>s.id===packageData.entries[0].claim.event.storyId);story.phone.historicalContacts=contacts.map(c=>({...structuredClone(c),canonicalName:c.canonicalName.toUpperCase()}));for(const c of contacts)story.phone.contactDisplayNames[c.id]='Synthetic preserved nickname';const before=structuredClone(story.phone.historicalContacts);const p=previewPhoneEvents(vault,packageData);assert.equal(p.accepted.length,1462);const n=applyPhoneEvents(vault,p,{confirmed:true});assert.deepEqual(n.stories.find(s=>s.id===story.id).phone.historicalContacts,before);assert.deepEqual(n.stories.find(s=>s.id===story.id).phone.contactDisplayNames,story.phone.contactDisplayNames);});
