import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyVault} from '../src/schema.js';
import {buildStoryContext} from '../src/prompt/context-builder.js';
import {assemblePrompt} from '../src/prompt/prompt-assembler.js';
import {runTurn} from '../src/chat/turn-engine.js';
import {serializePortableBackup,parseVesperBackup} from '../src/backup/vesper-backup.js';
import {prepareImport,commitPreparedImport} from '../src/migration/import-service.js';
import {loadVault,saveVaultAtomic} from '../src/storage/vault-store.js';
import {vaultDb} from '../test-support/vault-db.js';

function fixture(){
 const v=emptyVault('2026-01-01T00:00:00Z');v.personas=[{id:'p',name:'Amanda'}];v.characters=[{id:'x',name:'Character'}];
 v.stories=[{id:'s',title:'Story',personaId:'p',characterIds:['x']},{id:'other',title:'Other',personaId:'p',characterIds:['x']}];
 v.chats=[{id:'a',storyId:'s'},{id:'b',storyId:'s'},{id:'other-chat',storyId:'other'}];
 v.relationships=[{id:'ra',storyId:'s',chatId:'a',participantIds:['p','x'],stage:'friends',labels:['PRIVATE_A'],establishedFacts:[{id:'fa',text:'PRIVATE_A established fact.'}]},{id:'shared',storyId:'s',participantIds:['p','x'],stage:'friends',labels:['SHARED_STORY'],establishedFacts:[{id:'shared-fact',text:'SHARED_STORY established fact.'},{id:'nested-a',chatId:'a',text:'PRIVATE_A nested fact.'},{id:'nested-b',chatId:'b',text:'PRIVATE_B nested fact.'}]}];
 return v;
}
const prompt=(v,chatId='b',storyId='s')=>assemblePrompt({vault:v,storyId,chatId});
const context=(v,chatId='b',storyId='s')=>buildStoryContext(v,storyId,chatId);

test('chat-A relationship is excluded from chat B and included in A',()=>{const v=fixture();assert.ok(context(v,'a').relationships.some(r=>r.id==='ra'));assert.ok(!context(v).relationships.some(r=>r.id==='ra'));assert.equal(prompt(v,'a').relationship.id,'ra');assert.equal(prompt(v).relationship.id,'shared');assert.ok(!JSON.stringify(prompt(v)).includes('PRIVATE_A'));});
test('shared relationship retains eligibility in both chats',()=>{const v=fixture();for(const id of ['a','b'])assert.ok(context(v,id).relationships.some(r=>r.id==='shared'));v.relationships=v.relationships.filter(r=>r.id==='shared');for(const id of ['a','b'])assert.ok(JSON.stringify(prompt(v,id)).includes('SHARED_STORY'));});
test('nested chat-owned facts in a shared relationship are isolated',()=>{const v=fixture();v.relationships=v.relationships.filter(r=>r.id==='shared');assert.deepEqual(prompt(v,'a').relationship.establishedFacts.map(f=>f.id),['shared-fact','nested-a']);assert.deepEqual(prompt(v).relationship.establishedFacts.map(f=>f.id),['shared-fact','nested-b']);});
test('no fallback to another chat when shared relationship does not exist',()=>{const v=fixture();v.relationships=v.relationships.filter(r=>r.id==='ra');const p=prompt(v);assert.equal(p.relationship,null);assert.equal(p.canonAndContinuity.relationship,null);assert.equal(p.mateBondCanon,null);assert.deepEqual(context(v).relationships,[]);});
test('explicit chat ownership wins over a conflicting story scope label',()=>{const v=fixture();v.relationships[0].scope='story';assert.ok(!context(v).relationships.some(r=>r.id==='ra'));});
for(const scope of ['chat','scene'])test(`unowned ${scope}-scoped relationship cannot become shared fallback`,()=>{const v=fixture();v.relationships=[{id:'unowned',storyId:'s',scope,stage:'friends',labels:['UNOWNED_PRIVATE']}];for(const id of ['a','b'])assert.equal(prompt(v,id).relationship,null);assert.deepEqual(buildStoryContext(v,'s').relationships,[]);});
test('story-only context excludes owned relationships and nested chat facts',()=>{const v=fixture(),c=buildStoryContext(v,'s');assert.deepEqual(c.relationships.map(r=>r.id),['shared']);assert.deepEqual(c.relationships[0].establishedFacts.map(f=>f.id),['shared-fact']);});
test('null chat ownership keeps legacy story-wide relationship shared',()=>{const v=fixture();v.relationships=[{id:'legacy',storyId:'s',chatId:null,stage:'friends',establishedFacts:['Shared legacy fact.']}];for(const id of ['a','b'])assert.deepEqual(prompt(v,id).relationship,v.relationships[0]);});
test('wrong-story nested facts and other-story relationship states stay isolated',()=>{const v=fixture();v.relationships[1].establishedFacts.push({id:'wrong-story',storyId:'other',text:'FOREIGN_RELATIONSHIP_FACT'});v.relationships.push({id:'other-r',storyId:'other',chatId:'other-chat',stage:'friends',labels:['FOREIGN_RELATIONSHIP']});assert.ok(!JSON.stringify(prompt(v)).includes('FOREIGN_'));const p=prompt(v,'other-chat','other');assert.equal(p.relationship.id,'other-r');assert.ok(!JSON.stringify(p).includes('PRIVATE_A'));assert.ok(!JSON.stringify(p).includes('SHARED_STORY'));});
test('nested fact cannot contradict its owning relationship chat',()=>{const v=fixture();v.relationships[0].establishedFacts.push({id:'conflicting',chatId:'b',text:'CONFLICTING_FACT'});assert.ok(!JSON.stringify(prompt(v,'a')).includes('CONFLICTING_FACT'));assert.ok(!JSON.stringify(prompt(v)).includes('CONFLICTING_FACT'));});
test('chat-scoped facts inherit a matching parent owner, not a shared parent',()=>{const v=fixture();v.relationships[0].establishedFacts.push({id:'inherited',scope:'chat',text:'Inherited chat A fact.'});v.relationships[1].establishedFacts.push({id:'unowned-fact',scope:'chat',text:'UNOWNED_FACT'});assert.ok(JSON.stringify(prompt(v,'a')).includes('Inherited chat A fact.'));assert.ok(!JSON.stringify(context(v,'a')).includes('UNOWNED_FACT'));assert.ok(!JSON.stringify(prompt(v)).includes('UNOWNED_FACT'));});
test('chat-owned summaries remain isolated alongside relationship state',()=>{const v=fixture();v.memoryEntries=[{id:'summary-a',storyId:'s',chatId:'a',kind:'summary',status:'active',text:'PRIVATE_A summary.'}];assert.ok(JSON.stringify(prompt(v,'a')).includes('PRIVATE_A summary.'));assert.ok(!JSON.stringify(prompt(v)).includes('PRIVATE_A'));});
test('explicit story-scoped imported relationship memory remains shared',()=>{const v=fixture();v.memoryEntries=[{id:'imported',storyId:'s',chatId:'a',scope:'story',kind:'relationship',text:'Imported shared relationship memory.'}];for(const id of ['a','b'])assert.ok(prompt(v,id).memory.some(m=>m.id==='imported'));});
test('explicit chat-scoped relationship memory retains its ownership',()=>{const v=fixture();v.memoryEntries=[{id:'chat-memory',storyId:'s',chatId:'a',scope:'chat',kind:'relationship',text:'PRIVATE_A memory.'}];assert.ok(prompt(v,'a').memory.some(m=>m.id==='chat-memory'));assert.ok(!prompt(v).memory.some(m=>m.id==='chat-memory'));});
for(const nested of [false,true])test(`relationship-linked summary honors its source ownership (nested=${nested})`,()=>{const v=fixture();v.memoryEntries=[{id:'bad-summary',storyId:'s',chatId:'b',kind:'summary',status:'active',text:'PRIVATE_A derived summary.',...(nested?{data:{relationshipId:'ra'}}:{relationshipId:'ra'})},{id:'safe-summary',storyId:'s',chatId:'b',kind:'summary',status:'active',text:'SHARED_STORY summary.',relationshipId:'shared'}];const p=prompt(v);assert.ok(!JSON.stringify(p).includes('PRIVATE_A'));assert.ok(p.memory.some(m=>m.id==='safe-summary'));});
test('relationship-linked knowledge and nested shared facts honor source ownership',()=>{const v=fixture();v.knowledgeEntries=[{id:'bad-knowledge',storyId:'s',factKey:'private',value:'PRIVATE_A knowledge.',relationshipId:'ra'}];v.relationships[1].establishedFacts.push({id:'derived-fact',text:'PRIVATE_A derived fact.',relationshipId:'ra'});assert.ok(!JSON.stringify(prompt(v)).includes('PRIVATE_A'));});
test('missing relationship provenance produces no fallback',()=>{const v=fixture();v.memoryEntries=[{id:'orphan-summary',storyId:'s',chatId:'b',kind:'summary',status:'active',text:'ORPHAN_RELATIONSHIP_CONTEXT',relationshipId:'missing'}];assert.ok(!JSON.stringify(prompt(v)).includes('ORPHAN_'));});
test('chat switching and subsequent updates cannot contaminate another chat',()=>{const v=fixture();for(const id of ['a','b','a','b']){const p=prompt(v,id);if(id==='b')assert.ok(!JSON.stringify(p).includes('PRIVATE_A'));}v.relationships[0].labels.push('PRIVATE_A_UPDATE');v.relationships[0].establishedFacts.push({id:'updated',text:'PRIVATE_A_UPDATE fact.'});assert.ok(JSON.stringify(prompt(v,'a')).includes('PRIVATE_A_UPDATE'));assert.ok(!JSON.stringify(prompt(v)).includes('PRIVATE_A'));});
test('new chat receives only shared story-wide relationship facts',()=>{const v=fixture();v.chats.push({id:'new',storyId:'s'});const p=prompt(v,'new');assert.equal(p.relationship.id,'shared');assert.deepEqual(p.relationship.establishedFacts.map(f=>f.id),['shared-fact']);assert.ok(!JSON.stringify(p).includes('PRIVATE_'));});
test('relationship projection preserves stored ownership and facts',()=>{const v=fixture(),before=JSON.stringify(v);for(const id of ['a','b'])prompt(v,id);assert.equal(JSON.stringify(v),before);});
test('reload and portable backup/restore preserve relationship isolation',()=>{const v=fixture();for(const restored of [JSON.parse(JSON.stringify(v)),prepareImport(parseVesperBackup(serializePortableBackup(v))).vault]){assert.ok(!JSON.stringify(prompt(restored)).includes('PRIVATE_A'));assert.equal(prompt(restored,'a').relationship.id,'ra');assert.deepEqual(restored.relationships,v.relationships);}});
test('verified permanent milestone-derived shared relationship remains canonical in both chats',()=>{const v=fixture();v.messages=[{id:'proof',storyId:'s',chatId:'a',role:'user',ordinal:0,text:'Amanda and Character completed their mate bond.'}];v.milestones=[{id:'bond',storyId:'s',chatId:'a',type:'mated',status:'confirmed',participants:['p','x'],evidence:v.messages[0].text,sourceMessageId:'proof'}];v.relationships=[{id:'bond-r',storyId:'s',stage:'mated',participantIds:['p','x'],sourceMilestoneId:'bond',establishedFacts:[{id:'bond-fact',text:'Shared bond canon.',sourceMilestoneId:'bond'}]}];for(const id of ['a','b']){const p=prompt(v,id);assert.equal(p.relationship.stage,'mated');assert.ok(p.mateBondCanon);assert.equal(p.milestones[0].id,'bond');}});
test('scoped relationship exclusion does not rewrite verified permanent milestone membership',()=>{const v=fixture();v.messages=[{id:'proof',storyId:'s',chatId:'a',role:'user',ordinal:0,text:'Amanda and Character completed their mate bond.'}];v.milestones=[{id:'bond',storyId:'s',chatId:'a',type:'mated',status:'confirmed',participants:['p','x'],evidence:v.messages[0].text,sourceMessageId:'proof'}];v.relationships=[{id:'scoped',storyId:'s',chatId:'a',stage:'mated',participantIds:['p','x'],sourceMilestoneId:'bond'}];const p=prompt(v);assert.equal(p.relationship,null);assert.equal(p.milestones[0].id,'bond');assert.ok(p.mateBondCanon);});

async function requests(v,chatId,duringRepair=false){const bodies=[],oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage;globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_url,options)=>{bodies.push(JSON.parse(options.body));if(bodies.length===1&&duringRepair)v.relationships[0].chatId='a';return {ok:true,json:async()=>({choices:[{message:{content:bodies.length===1?'Amanda decided to leave.':'The evening settled quietly.'}}]})};};try{await runTurn({vault:v,storyId:'s',chatId,model:'synthetic'});assert.equal(bodies.length,2);return bodies;}finally{globalThis.fetch=oldFetch;if(oldStorage===undefined)delete globalThis.localStorage;else globalThis.localStorage=oldStorage;}}
test('provider and repair payloads exclude chat-A relationship context from B',async()=>{const v=fixture();v.memoryEntries=[{id:'derived-summary',storyId:'s',chatId:'b',kind:'summary',status:'active',text:'PRIVATE_A repair summary.',relationshipId:'ra'}];for(const body of await requests(v,'b')){assert.ok(!JSON.stringify(body).includes('PRIVATE_A'));assert.ok(JSON.stringify(body).includes('SHARED_STORY'));}});
test('provider and repair payloads include a relationship in its owning chat',async()=>{for(const body of await requests(fixture(),'a'))assert.ok(JSON.stringify(body).includes('PRIVATE_A'));});
test('repair refresh cannot retain relationship ownership changed during a turn',async()=>{const v=fixture();v.relationships[0].chatId='b';const bodies=await requests(v,'b',true);assert.ok(JSON.stringify(bodies[0]).includes('PRIVATE_A'));assert.ok(!JSON.stringify(bodies[1]).includes('PRIVATE_A'));});
test('real save paths retain ownership after reload, replacement restore, and conflict',async()=>{const db=vaultDb(),v=await loadVault(db);Object.assign(v,fixture());await saveVaultAtomic(db,v);const stale=await loadVault(db),fresh=await loadVault(db);fresh.relationships[0].labels.push('PRIVATE_A_NEWER');await saveVaultAtomic(db,fresh);const before=JSON.stringify(await loadVault(db));await assert.rejects(saveVaultAtomic(db,stale),e=>e.code==='VESPER_VAULT_CONFLICT');assert.equal(JSON.stringify(await loadVault(db)),before);const current=await loadVault(db),prepared=prepareImport(parseVesperBackup(serializePortableBackup(current)));await commitPreparedImport(db,prepared,{expectedRevision:current.storageRevision});assert.ok(!JSON.stringify(prompt(await loadVault(db))).includes('PRIVATE_A'));});
