import test from 'node:test';import assert from 'node:assert/strict';
import {emptyVault} from '../src/schema.js';import {runTurn} from '../src/chat/turn-engine.js';import {assemblePrompt} from '../src/prompt/prompt-assembler.js';import {validateModelOutput} from '../src/validation/output-gate.js';import {projectRoleplayContext,roleplayMetaIssues} from '../src/chat/roleplay-integrity.js';
const oldMeta='The story has reached a complete conclusion. No continuation is necessary.';
const newMeta='Understood. The scene concluded with a complete narrative beat—Character’s quiet declaration of love carried on the bond as Player sleeps, the circle of their story’s opening chapter closed. Future responses will end on complete sentences and resolved narrative moments.';
const fixture=()=>({...emptyVault(),personas:[{id:'p',name:'Player'}],characters:[{id:'x',name:'Character'}],stories:[{id:'s',title:'Synthetic integrity',personaId:'p',characterIds:['x']}],chats:[{id:'c',storyId:'s'}],messages:[{id:'u',storyId:'s',chatId:'c',role:'user',ordinal:0,text:'I stay beside you.'},{id:'meta',storyId:'s',chatId:'c',role:'assistant',ordinal:1,text:newMeta},{id:'good',storyId:'s',chatId:'c',role:'assistant',ordinal:2,text:'Character looked toward the garden.'}]});
for(const text of [oldMeta,newMeta,'Understood. Future replies will preserve continuity.','The opening chapter of your story is closed; no further roleplay is needed.','No further narration is required.','I will ensure future responses end on complete narrative beats.'])test('shared output gate rejects writing-process/end commentary: '+text.slice(0,40),()=>{for(const personaDraft of [false,true]){const result=validateModelOutput({text,personaDraft,persona:{name:'Player'}});assert.equal(result.ok,false);assert.ok(result.issues.some(i=>i.type==='roleplay-meta'));}});
for(const text of ['Character completed his report.','The chapter ended at the library door.','A peaceful morning followed their established bond.','Character said, "The story is complete," and shut the book.','"No continuation is necessary," Character said about the cancelled television serial.','I close the book and say, "The chapter is finished."'])test('legitimate in-world endings/dialogue remain valid: '+text.slice(0,40),()=>assert.deepEqual(roleplayMetaIssues(text),[]));
async function capture(v,text,options={}){const fetch=globalThis.fetch,storage=globalThis.localStorage,calls=[];globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_,o)=>{calls.push(JSON.parse(o.body));return {ok:true,json:async()=>({choices:[{message:{content:text}}]})};};try{return {result:await runTurn({vault:v,storyId:'s',chatId:'c',model:'synthetic/model',...options}),calls};}finally{globalThis.fetch=fetch;if(storage===undefined)delete globalThis.localStorage;else globalThis.localStorage=storage;}}
for(const options of [{},{personaDraft:true},{director:true,oocInstruction:'Skip sleep.'},{oocInstruction:'Continue the scene.'},{oocInstruction:'Elaborate the response.'},{opening:true}])test('all generation modes reject meta with no automatic extra request '+JSON.stringify(options),async()=>{const v=fixture(),before=structuredClone(v),{result,calls}=await capture(v,newMeta,options);assert.equal(result.blocked,true);assert.equal(calls.length,1);assert.ok(!JSON.stringify(calls).includes('quiet declaration of love'));assert.match(calls[0].messages.at(-1).content,/Only the user/);assert.deepEqual(v,before);});
test('source-linked and transitive meta derivatives stay out of context across reload',()=>{const v=fixture();v.memoryEntries=[{id:'bad',storyId:'s',kind:'canon',text:'DERIVED_META_SECRET',sourceMessageIds:['meta']},{id:'transitive',storyId:'s',kind:'summary',text:'TRANSITIVE_SECRET',sourceMemoryIds:['bad']},{id:'unsourced',storyId:'s',kind:'summary',text:newMeta},{id:'safe',storyId:'s',chatId:'c',kind:'summary',text:'SAFE_SOURCE_FACT',sourceMessageIds:['good']}];v.knowledgeEntries=[{id:'k',storyId:'s',knowerId:'x',value:'KNOWLEDGE_SECRET',sourceMemoryIds:['transitive']}];v.sceneStates=[{id:'scene',storyId:'s',chatId:'c',location:'SCENE_SECRET',sourceMessageId:'meta'}];const before=structuredClone(v);for(const source of [v,JSON.parse(JSON.stringify(v))]){const context=JSON.stringify(assemblePrompt({vault:source,storyId:'s',chatId:'c'}));for(const secret of ['DERIVED_META_SECRET','TRANSITIVE_SECRET','KNOWLEDGE_SECRET','SCENE_SECRET','quiet declaration of love'])assert.ok(!context.includes(secret),secret);assert.ok(context.includes('SAFE_SOURCE_FACT'));}assert.deepEqual(v,before);});
test('user-authored text and safe authoritative correction remain model-visible',()=>{const v=fixture();v.messages[0].text='Do not write "Future responses will end on complete sentences".';v.messages[1].text='CORRECTED_SCENE_FACT';v.messages[1].editAuthority={version:1,withheldContextKeys:[]};v.messages[1].editedAt='2026-01-01';assert.ok(JSON.stringify(assemblePrompt({vault:v,storyId:'s',chatId:'c'})).includes('CORRECTED_SCENE_FACT'));assert.ok(projectRoleplayContext(v).messages.some(m=>m.id==='u'));});
test('meta derivative exclusion does not remove independent canon or forgotten tombstones',()=>{const v=fixture();v.memoryEntries=[{id:'tomb',storyId:'s',kind:'canon',status:'forgotten',text:newMeta},{id:'safe',storyId:'s',kind:'canon',text:'Safe independent history.',sourceMessageIds:['good']}];const n=projectRoleplayContext(v);assert.deepEqual(n.memoryEntries,v.memoryEntries);assert.deepEqual(n.personas,v.personas);assert.deepEqual(n.stories,v.stories);});
test('all modes respect explicit user-set story completion before any provider call',async()=>{for(const options of [{},{personaDraft:true},{director:true}]){const v=fixture();v.stories[0].status='finished';await assert.rejects(()=>capture(v,'Morning light filled the room.',options),/explicitly marked finished/);}});
test('safe My Turn still writes editable protagonist contribution',async()=>{const {result}=await capture(fixture(),'I smile and open my eyes.',{personaDraft:true});assert.equal(result.blocked,false);});
