import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyVault} from '../src/schema.js';
import {ensureStoryPhone,openPrivateThread} from '../src/phone/phone-state.js';
import {runPhoneTurn} from '../src/phone/phone-engine.js';
import {runTurn} from '../src/chat/turn-engine.js';
import {sendOpenRouterChat} from '../src/provider/openrouter.js';
const fixture=()=>({...emptyVault(),personas:[{id:'p',name:'Player'}],characters:[{id:'x',name:'Character X'},{id:'y',name:'Character Y'}],stories:[{id:'s',title:'Synthetic audit',personaId:'p',characterIds:['x','y'],settings:{model:'synthetic/model'}}],chats:[{id:'c',storyId:'s'}],messages:[{id:'u',storyId:'s',chatId:'c',role:'user',ordinal:0,text:'I look toward the garden.',audienceIds:['p','x']}]});
async function mocked(response,fn){const f=globalThis.fetch,s=globalThis.localStorage,calls=[];globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_,o)=>{calls.push(JSON.parse(o.body));return {ok:true,status:200,json:async()=>response};};try{return {value:await fn(),calls};}finally{globalThis.fetch=f;if(s===undefined)delete globalThis.localStorage;else globalThis.localStorage=s;}}
test('phone context cannot disclose direct or transitive private audience facts',async()=>{
 let v=ensureStoryPhone(fixture(),'s','c');const r=openPrivateThread(v,'s','c','y');v=r.vault;
 v.memoryEntries=[{id:'direct',storyId:'s',kind:'canon',status:'active',text:'DIRECT_PRIVATE_SECRET',audienceIds:['p','x']},{id:'source',storyId:'s',kind:'summary',chatId:'c',text:'SOURCE_PRIVATE_SECRET',sourceMessageIds:['u']},{id:'derived',storyId:'s',kind:'canon',text:'TRANSITIVE_PRIVATE_SECRET',sourceMemoryIds:['source']},{id:'safe',storyId:'s',kind:'canon',text:'SHARED_SAFE_FACT'}];
 v.loreEntries=[{id:'private-lore',scope:'story',storyId:'s',text:'PRIVATE_LORE',audienceIds:['p','x']}];v.relationships=[{id:'r',storyId:'s',participantIds:['p','y'],establishedFacts:[{text:'PRIVATE_NESTED_FACT',audienceIds:['p','x']}]}];
 let payload;await runPhoneTurn({vault:v,storyId:'s',threadId:r.threadId,action:'continue',send:async options=>{payload=JSON.stringify(options);return {choices:[{message:{content:'[{"speakerId":"y","text":"The garden gate is open."}]'}}]};}});
 for(const secret of ['DIRECT_PRIVATE_SECRET','SOURCE_PRIVATE_SECRET','TRANSITIVE_PRIVATE_SECRET','PRIVATE_LORE','PRIVATE_NESTED_FACT'])assert.ok(!payload.includes(secret),secret);assert.ok(payload.includes('SHARED_SAFE_FACT'));
 const own=openPrivateThread(v,'s','c','x');await runPhoneTurn({vault:own.vault,storyId:'s',threadId:own.threadId,action:'continue',send:async options=>{payload=JSON.stringify(options);return {choices:[{message:{content:'[{"speakerId":"x","text":"The garden gate is open."}]'}}]};}});for(const secret of ['DIRECT_PRIVATE_SECRET','SOURCE_PRIVATE_SECRET','TRANSITIVE_PRIVATE_SECRET','PRIVATE_LORE'])assert.ok(payload.includes(secret),secret);
});
for(const response of [{error:{message:'Synthetic provider failure'}},{choices:[]},{choices:[{message:{content:{unexpected:true}}}]}])test('malformed successful provider response fails clearly without another request '+JSON.stringify(response),async()=>{await assert.rejects(()=>mocked(response,()=>sendOpenRouterChat({model:'synthetic/model',messages:[]})),/provider|reply|response/i);});
test('a hard-blocked generation never automatically purchases repair requests',async()=>{const {value,calls}=await mocked({choices:[{message:{content:'Mandy entered the garden.'}}]},()=>runTurn({vault:fixture(),storyId:'s',chatId:'c',model:'synthetic/model',repairAttempts:0}));assert.equal(value.blocked,true);assert.equal(calls.length,1);});
test('requests lacking provider usage are still counted',async()=>{const {value,calls}=await mocked({choices:[{message:{content:'Character X opened the garden gate.'}}]},()=>runTurn({vault:fixture(),storyId:'s',chatId:'c',model:'synthetic/model'}));assert.equal(calls.length,1);assert.equal(value.usage.length,1);});
import {validateModelOutput} from '../src/validation/output-gate.js';
import {listStoryChoices,storyIsRunnable} from '../src/library/story-selection.js';
import {scanMilestoneEvents} from '../src/milestones/events.js';
test('an NPC named Amanda must not be confused with a differently named protagonist',()=>{const result=validateModelOutput({text:'Amanda kissed Character X.',persona:{name:'Morgan'},characters:[{name:'Amanda'},{name:'Character X'}]});assert.ok(!result.issues.some(i=>i.type==='user-agency'));assert.ok(validateModelOutput({text:'Morgan kissed Character X.',persona:{name:'Morgan'}}).issues.some(i=>i.type==='user-agency'));});
test('library selection uses the current assigned persona rather than historical ownership',()=>{const v=fixture();v.personas.push({id:'new',name:'Current protagonist'});v.stories[0].personaBinding={personaId:'new',history:[]};assert.equal(listStoryChoices(v)[0].personaName,'Current protagonist');assert.equal(storyIsRunnable(v,'s').persona.id,'new');});
test('research about a completed bond cannot automatically establish a mate bond',()=>{const v=fixture();for(const text of ['Player and Character X are researching a completed mate bond.',"Player and Character X are watching Guest's first kiss."]){v.messages[0].text=text;const n=scanMilestoneEvents(v,['u']);assert.ok(!n.milestones.some(m=>m.status==='confirmed'),text);}v.messages[0].text='Player and Character X completed their mate bond.';assert.ok(scanMilestoneEvents(v,['u']).milestones.some(m=>m.status==='confirmed'&&m.type==='mated'));});
test('truncated responses are withheld with no automatic extra query',async()=>{const {value,calls}=await mocked({choices:[{finish_reason:'length',message:{content:'Character X opened the garden gate.'}}]},()=>runTurn({vault:fixture(),storyId:'s',chatId:'c',model:'synthetic/model',repairAttempts:0}));assert.equal(value.blocked,true);assert.equal(calls.length,1);assert.ok(value.validation.issues.some(i=>i.type==='incomplete-output'));});
test('explicitly finished stories also block phone generation before any query',async()=>{let v=ensureStoryPhone(fixture(),'s','c');const r=openPrivateThread(v,'s','c','x');v=r.vault;v.stories[0].status='finished';let calls=0;await assert.rejects(()=>runPhoneTurn({vault:v,storyId:'s',threadId:r.threadId,action:'continue',send:async()=>{calls++;}}),/explicitly marked finished/);assert.equal(calls,0);});

test('truncated phone replies are rejected without a retry and retain reported usage',async()=>{const v=ensureStoryPhone(fixture(),'s','c'),r=openPrivateThread(v,'s','c','x');let calls=0;await assert.rejects(()=>runPhoneTurn({vault:r.vault,storyId:'s',threadId:r.threadId,action:'continue',send:async()=>{calls++;return {choices:[{finish_reason:'length',message:{content:'[{"speakerId":"x","text":"The gate is open."}]'}}],usage:{completion_tokens:3}};}}),error=>/truncated/.test(error.message)&&error.phoneUsage.completion_tokens===3);assert.equal(calls,1);});
import {recordUsage} from '../src/usage/usage-ledger.js';
test('malformed provider token metadata cannot corrupt saved accounting',()=>{for(const tokens of ['10',-1,Infinity,NaN,{}]){const row=recordUsage({model:'synthetic/model',promptTokens:tokens,completionTokens:2});assert.equal(row.promptTokens,0);assert.equal(row.totalTokens,2);}});
import {assemblePrompt} from '../src/prompt/prompt-assembler.js';
test('ordinary provider and explicit repair context cannot reveal private audience derivatives',async()=>{const v=fixture();v.messages[0].text='PRIVATE_TRANSCRIPT';v.messages[0].role='assistant';v.messages[0].editAuthority={version:1,withheldContextKeys:[]};v.messages.push({id:'visible',storyId:'s',chatId:'c',role:'user',ordinal:1,text:'I look at the garden.'});v.memoryEntries=[{id:'private',storyId:'s',kind:'canon',text:'PRIVATE_MEMORY',sourceMessageIds:['u']},{id:'derived',storyId:'s',kind:'canon',text:'PRIVATE_DERIVATIVE',sourceMemoryIds:['private']},{id:'safe',storyId:'s',kind:'canon',text:'PUBLIC_CANON'}];v.loreEntries=[{id:'private-lore',scope:'story',storyId:'s',text:'PRIVATE_LORE',audienceIds:['p','x']}];const prompt=JSON.stringify(assemblePrompt({vault:v,storyId:'s',chatId:'c'}));for(const word of ['PRIVATE_TRANSCRIPT','PRIVATE_MEMORY','PRIVATE_DERIVATIVE','PRIVATE_LORE'])assert.ok(!prompt.includes(word),word);assert.ok(prompt.includes('PUBLIC_CANON'));const old=fetch,storage=globalThis.localStorage,bodies=[];globalThis.localStorage={getItem:()=> 'synthetic-key'};globalThis.fetch=async(_u,o)=>{bodies.push(JSON.parse(o.body));return {ok:true,json:async()=>({choices:[{message:{content:bodies.length===1?'Your move.':'Character Y opened the gate.'}}]})};};try{await runTurn({vault:v,storyId:'s',chatId:'c',model:'synthetic/model',repairAttempts:1});assert.equal(bodies.length,2);assert.ok(!JSON.stringify(bodies).includes('PRIVATE_'));}finally{globalThis.fetch=old;if(storage===undefined)delete globalThis.localStorage;else globalThis.localStorage=storage;}});

import {playerContinuity} from '../src/chat/player-continuity.js';
test('My Turn history only exposes explicitly restricted evidence to its owning protagonist',()=>{const v=fixture();v.messages[0].audienceIds=['x'];v.messages[0].text='I want PRIVATE_PREFERENCE.';assert.equal(playerContinuity(v,'s','c').messages.length,0);v.messages[0].audienceIds=['p','x'];assert.equal(playerContinuity(v,'s','c').messages.length,1);});
