import test from 'node:test';import assert from 'node:assert/strict';
import {phoneFixture,groupSources,privateSources,time} from './fixtures/story-phone-formats.js';
import {scanPhoneHistory,applyPhoneHistory,resolvePhoneHistoryCandidate} from '../src/phone/phone-history.js';
import {getPhoneContacts,validateStoryPhone,updatePhoneThread} from '../src/phone/phone-state.js';
import {buildPhoneContext} from '../src/phone/phone-context.js';import {runPhoneTurn} from '../src/phone/phone-engine.js';
import {serializePortableBackup,parseVesperBackup} from '../src/backup/vesper-backup.js';
const rows=v=>(v.stories[0].phone?.threads||[]).flatMap(t=>t.messages);
const scan=v=>scanPhoneHistory(v,'s');
const mapped={Amanda:'p',AMANDA:'p',DANE:'d',Dane:'d',LUCIEN:'l',Lucien:'l',Lucian:'l',RHYDIAN:'r',Rhydian:'r'};
function resolution(c,v,extra={}){return {confirmed:true,identities:mapped,targetThreadId:c.kind==='group'?v.stories[0].phone.threads[0].id:undefined,...extra};}
function accept(v,p=scan(v),extra={}){const resolutions=Object.fromEntries(p.candidates.filter(c=>!c.issues.some(i=>['recipients','continuation','time','delivery'].includes(i))).map(c=>[c.key,resolution(c,v,extra)]));return applyPhoneHistory(v,p,{confirmed:true,selectedKeys:Object.keys(resolutions),resolutions},time);}
test('real-format inline, bold and multiline private messages preserve complete exact bodies',()=>{const v=phoneFixture(privateSources.slice(0,2)),p=scan(v);assert.ok(p.candidates.length>=3);const c=p.candidates.find(c=>c.senderLabel==='AMANDA');assert.equal(c.text,'I repaired your pendant.\n\nThe original seal is unchanged.');assert.ok(p.candidates.some(c=>c.text==='Thank you.\n\nI will collect it tomorrow.'));const n=accept(v,p);assert.ok(rows(n).some(m=>m.text===c.text));validateStoryPhone(n.stories[0],n);});
test('supporting contact proposals are read-only and never join Story Cast automatically',()=>{const v=phoneFixture(privateSources.slice(2)),old=structuredClone(v),p=scan(v);assert.ok(p.contactProposals.some(c=>c.label==='Maribel'));assert.ok(p.contactProposals.some(c=>c.label==='Mrs. Pell'));assert.deepEqual(v,old);assert.equal(getPhoneContacts(v,'s').length,3);});
test('reviewed NPC contact identity supports private texts and portable restore without character creation',()=>{const v=phoneFixture(['Amanda’s phone buzzed.\n\nMARIBEL: The gate is open.']),p=scan(v),c=p.candidates[0];assert.ok(c);const n=applyPhoneHistory(v,p,{confirmed:true,selectedKeys:[c.key],resolutions:{[c.key]:{confirmed:true,identities:mapped,newContacts:[{label:'MARIBEL',canonicalName:'Maribel'}]}}},time);assert.equal(n.characters.length,v.characters.length);assert.equal(getPhoneContacts(n,'s').length,4);assert.deepEqual(n.stories[0].phone.threads[0].participantIds,['d','l','r']);assert.equal(rows(n)[0].text,'The gate is open.');const restored=parseVesperBackup(serializePortableBackup(n));assert.deepEqual(rows(restored),rows(n));assert.deepEqual(buildPhoneContext(n,{storyId:'s',chatId:'c',respondingCharacterIds:['d']}),[]);});
test('group renames retain one original conversation and historical exits exclude departed recipient',()=>{const v=phoneFixture(groupSources),p=scan(v);assert.ok(p.candidates.length>=9);const group=p.candidates.filter(c=>c.kind==='group');assert.equal(new Set(group.map(c=>c.conversationKey)).size,1);const absence=group.filter(c=>['He left.','That was quick.'].includes(c.text));assert.equal(absence.length,2);assert.ok(absence.every(c=>!c.participantLabels.some(x=>/^Dane$/i.test(x))));const n=accept(v,p,{membershipConfirmed:true,distinct:true});assert.equal(n.stories[0].phone.threads.filter(t=>t.kind==='group').length,1);assert.ok(rows(n).find(m=>m.text==='He left.').audienceIds.every(id=>id!=='d'));assert.ok(!buildPhoneContext(n,{storyId:'s',chatId:'c',respondingCharacterIds:['d']}).some(m=>m.text==='He left.'));});
test('observed duplicate user/screen depictions are withheld as echoes rather than extra ready messages',()=>{const v=phoneFixture(groupSources),p=scan(v);assert.equal(p.candidates.filter(c=>c.text==='Meet by the gate.'&&c.status==='ready').length<=1,true);assert.ok(p.echoCount>=1);});
test('bold text from explicitly identified sender supports the supplied clock without inventing dates',()=>{const v=phoneFixture(['Amanda’s phone buzzed with a text from Dane Calder.\n\n**DANE CALDER: A neutral gate update.**']),p=scan(v);assert.equal(p.candidates[0].text,'A neutral gate update.');assert.equal(p.candidates[0].createdAt,null);});
test('third-party Dane/Tessa texts retain actual audiences and are archive-only without Amanda knowledge',()=>{const v=phoneFixture(['Dane pulled out his phone and sent Tessa a message.\n\nDANE: Did you check the gate?\n\nHis phone vibrated.\n\nTESSA: The gate is secure.']),p=scan(v);assert.equal(p.candidates.length,2);const n=accept(v,p,{newContacts:[{label:'TESSA',canonicalName:'Tessa'}]});const all=rows(n);assert.equal(all.length,2);assert.ok(all.every(m=>!m.audienceIds.includes('p')));assert.ok(n.stories[0].phone.threads.find(t=>t.messages.length).historicalOnly);assert.deepEqual(buildPhoneContext(n,{storyId:'s',chatId:'c',respondingCharacterIds:['l']}),[]);assert.ok(buildPhoneContext(n,{storyId:'s',chatId:'c',respondingCharacterIds:['d']}).length===2);});
test('archive-only NPC or third-party threads cannot dispatch generation',async()=>{const v=phoneFixture(['Amanda’s phone buzzed.\n\nMARIBEL: Gate update.']),p=scan(v),n=accept(v,p,{newContacts:[{label:'MARIBEL',canonicalName:'Maribel'}]});const t=n.stories[0].phone.threads.find(t=>t.messages.length);let calls=0;await assert.rejects(runPhoneTurn({vault:n,storyId:'s',threadId:t.id,action:'continue',send:async()=>{calls++;}}),/historical|archive|read.only/i);assert.equal(calls,0);});
for(const text of ['Amanda drafted a message in her notes app:\n\nAMANDA: Not sent.','The voicemail transcription identified Celestine Arrow.\n\nCELESTINE: Please call me.','Amanda answered her phone.\n\nDANE: Hello.','OOC • Summary: Amanda texted everyone.\n\nDANE: Invented example.','Rhydian: enormous, royal, amber-eyed.\nLucien: immaculate.'])test('non-text material stays outside recovery: '+text.split('\n')[0],()=>{assert.equal(scan(phoneFixture([text])).candidates.length,0);});
test('PHONE sender tag without documented recipients remains withheld',()=>{const p=scan(phoneFixture(['His phone appeared. One text.\n\n[[PHONE:Dante Verro]]Kitchen. A neutral order. [[/PHONE]]']));assert.equal(p.candidates.length,1);assert.ok(p.candidates[0].issues.includes('recipients'));});
test('extended recovery provenance and aliases reject coordinated recipient tampering on restore',()=>{const v=phoneFixture(['Amanda’s phone buzzed with a text from Dane Calder.\n\n**DANE CALDER: Gate update.**']),p=scan(v),n=accept(v,p);assert.equal(rows(n).length,1);const bad=structuredClone(n);rows(bad)[0].audienceIds.push('l');assert.throws(()=>parseVesperBackup(serializePortableBackup(bad)));});
test('new formats remain isolated across story chats and story changes',()=>{const v=phoneFixture(['Amanda’s phone buzzed with a text from Dane Calder.\n\nDANE CALDER: Only chat one.']);v.messages.push({...v.messages[0],id:'m2',chatId:'c2',text:v.messages[0].text.replace('Only chat one.','Only chat two.')});const n=accept(v);assert.deepEqual(buildPhoneContext(n,{storyId:'s',chatId:'c',respondingCharacterIds:['d']}).map(m=>m.text),['Only chat one.']);assert.deepEqual(buildPhoneContext(n,{storyId:'other',chatId:'oc',respondingCharacterIds:['d']}),[]);});
test('narrative cue labels never become proposed contacts',()=>{const p=scan(phoneFixture(['Amanda’s phone buzzed.\n\nThen immediately:\n\nDANE: Gate update.\n\nRespectfully: no new contact.']));assert.ok(!p.contactProposals.some(c=>/Then|Respectfully/.test(c.label)));});
test('multiline PHONE tags keep exact bodies and withhold missing recipients',()=>{const p=scan(phoneFixture(['His phone lit up.\n[[PHONE:Dane Calder]]\nFirst line.\n\nSecond line.\n[[/PHONE]]']));const c=p.candidates.find(c=>c.format==='phone-tag');assert.equal(c.text,'\nFirst line.\n\nSecond line.\n');assert.ok(c.issues.includes('recipients'));});
test('unlabelled screen text requires sender and recipient evidence before import',()=>{const v=phoneFixture(['Her phone buzzed.\nShe typed:\n\n**A neutral reply.**\n\nShe hit send.']),p=scan(v);assert.equal(p.candidates.length,1);assert.ok(p.candidates[0].issues.includes('sender'));assert.throws(()=>resolvePhoneHistoryCandidate(v,p.candidates[0],{confirmed:true}),/sender|recipients|source/i);});
test('private device ownership never carries into an unrelated later source record',()=>{const v=phoneFixture(['Amanda’s phone buzzed.\n\nDANE: First source.','His phone buzzed.\n\nTESSA: An unrelated private reply.']),p=scan(v),c=p.candidates.find(c=>c.senderLabel==='TESSA');assert.ok(!c||c.issues.includes('recipients'));assert.ok(!c||!c.participantLabels.includes('Amanda'));});

test('regeneration discards obsolete NPC archive identities without leaving invalid backup references',async()=>{const {prepareVaultRegeneration}=await import('../src/chat/regeneration.js');const v=phoneFixture(['Amanda’s phone buzzed.\n\nMARIBEL: A neutral update.']),p=scan(v),n=accept(v,p,{newContacts:[{label:'MARIBEL',canonicalName:'Maribel'}]});const old=structuredClone(n),plan=prepareVaultRegeneration(n,'m0');assert.deepEqual(n,old);validateStoryPhone(plan.vault.stories[0],plan.vault);assert.equal(rows(plan.vault).length,0);parseVesperBackup(serializePortableBackup(plan.vault));});
test('forgetting a historical source hides its recovered contact text while preserving stored history',()=>{const v=phoneFixture(['Amanda’s phone buzzed with a text from Dane Calder.\n\nDANE CALDER: A private gate update.']),n=accept(v);assert.equal(rows(n).length,1);n.messages[0].status='forgotten';assert.deepEqual(buildPhoneContext(n,{storyId:'s',chatId:'c',respondingCharacterIds:['d']}),[]);assert.equal(rows(n).length,1);validateStoryPhone(n.stories[0],n);});
test('group membership requires explicit historical audience confirmation even with known aliases',()=>{const v=phoneFixture(groupSources),p=scan(v),c=p.candidates.find(c=>c.kind==='group'&&!c.issues.includes('repeat'));assert.throws(()=>resolvePhoneHistoryCandidate(v,c,resolution(c,v)),/historical membership/i);});
test('new archival thread metadata rejects corrupt ownership flags on restore',()=>{const v=phoneFixture(['Amanda’s phone buzzed.\n\nMARIBEL: Gate update.']),n=accept(v,scan(v),{newContacts:[{label:'MARIBEL',canonicalName:'Maribel'}]});n.stories[0].phone.threads.find(t=>t.historicalOnly).historicalOnly='yes';assert.throws(()=>parseVesperBackup(serializePortableBackup(n)));});
test('a phone merely present in a room does not convert spoken dialogue into texts',()=>{const p=scan(phoneFixture(['Amanda’s phone lay on the table. Dane spoke aloud.\n\nDANE: A spoken greeting.']));assert.equal(p.candidates.length,0);});
test('coordinated archival alias tampering cannot introduce another story’s character',()=>{const v=phoneFixture(['Amanda’s phone buzzed.\n\nMARIBEL: Gate update.']);v.characters.push({id:'foreign',name:'Foreign Character'});v.stories[1].characterIds.push('foreign');const n=accept(v,scan(v),{newContacts:[{label:'MARIBEL',canonicalName:'Maribel'}]}),m=rows(n)[0],old=m.senderId;m.senderId='foreign';m.audienceIds=m.audienceIds.map(id=>id===old?'foreign':id);m.recovery.identities=m.recovery.identities.map(i=>i.id===old?{...i,id:'foreign'}:i);n.stories[0].phone.historicalAliases.find(a=>a.id===old).id='foreign';assert.throws(()=>parseVesperBackup(serializePortableBackup(n)));});
test('italic internal thoughts beside a phone notification are not text messages',()=>{const p=scan(phoneFixture(['Amanda’s phone buzzed with a message.\n\n*A neutral internal thought.*\n\nShe remembered the earlier message.']));assert.equal(p.candidates.length,0);});
test('regeneration retains reviewed aliases still supported by surviving private messages',async()=>{const {prepareVaultRegeneration}=await import('../src/chat/regeneration.js');const v=phoneFixture(['Amanda’s phone buzzed.\n\nDANE: First update.','Amanda’s phone buzzed.\n\nDANE: Second update.']),n=accept(v),plan=prepareVaultRegeneration(n,'m1');assert.equal(rows(plan.vault).length,1);assert.equal(rows(plan.vault)[0].text,'First update.');parseVesperBackup(serializePortableBackup(plan.vault));});
test('regeneration retains an NPC contact with surviving source evidence',async()=>{const {prepareVaultRegeneration}=await import('../src/chat/regeneration.js');const v=phoneFixture(['Amanda’s phone buzzed.\n\nMARIBEL: First update.','Amanda’s phone buzzed.\n\nMARIBEL: Second update.']),n=accept(v,scan(v),{newContacts:[{label:'MARIBEL',canonicalName:'Maribel'}]}),plan=prepareVaultRegeneration(n,'m1');assert.equal(rows(plan.vault).length,1);assert.equal(plan.vault.stories[0].phone.historicalContacts.length,1);parseVesperBackup(serializePortableBackup(plan.vault));});
test('reviewed short-name aliases cannot bypass duplicate checks against native phone messages',async()=>{const {openPrivateThread,appendPhoneMessage}=await import('../src/phone/phone-state.js');const v=phoneFixture(['Amanda’s phone buzzed.\n\nDANE: An existing update.']);const opened=openPrivateThread(v,'s','c','d',time),n=appendPhoneMessage(opened.vault,'s',opened.threadId,{senderType:'character',senderId:'d',text:'An existing update.'},time),p=scan(n);assert.throws(()=>resolvePhoneHistoryCandidate(n,p.candidates[0],resolution(p.candidates[0],n)),/existing|repeat|distinct/i);});
test('regeneration removes only an obsolete archival contact nickname when its last source is discarded',async()=>{const {prepareVaultRegeneration}=await import('../src/chat/regeneration.js'),{setContactDisplayName}=await import('../src/phone/phone-state.js');const v=phoneFixture(['Amanda’s phone buzzed.\n\nMARIBEL: A neutral update.']),n=accept(v,scan(v),{newContacts:[{label:'MARIBEL',canonicalName:'Maribel'}]}),id=n.stories[0].phone.historicalContacts[0].id,named=setContactDisplayName(n,'s',id,'Friend');const plan=prepareVaultRegeneration(named,'m0');assert.equal(plan.vault.stories[0].phone.contactDisplayNames[id],undefined);parseVesperBackup(serializePortableBackup(plan.vault));});
test('malformed extended source bounds are rejected during restore',()=>{const v=phoneFixture(['Amanda’s phone buzzed.\n\nDANE: A neutral update.']),n=accept(v);rows(n)[0].recovery.headerStart=-1;assert.throws(()=>parseVesperBackup(serializePortableBackup(n)));});

test('native historical recipients remain valid after a character leaves the current story cast',async()=>{
 const {appendPhoneMessage}=await import('../src/phone/phone-state.js');
 const v=phoneFixture([]),s=v.stories[0],thread=s.phone.threads[0];
 let next=appendPhoneMessage(v,s.id,thread.id,{senderType:'character',senderId:'l',text:'Synthetic prior group update.'});
 next=updatePhoneThread(next,s.id,thread.id,{participantIds:['d','r']});
 next.stories[0].characterIds=next.stories[0].characterIds.filter(id=>id!=='l');
 const historical=structuredClone(rows(next));
 validateStoryPhone(next.stories[0],next);
 const restored=parseVesperBackup(serializePortableBackup(next));
 assert.deepEqual(rows(restored),historical);
 assert.deepEqual(buildPhoneContext(restored,{storyId:'s',chatId:'c',respondingCharacterIds:['d']}).map(m=>m.text),['Synthetic prior group update.']);
 assert.deepEqual(buildPhoneContext(restored,{storyId:'s',chatId:'c',respondingCharacterIds:['l']}),[]);
});
