import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyVault} from '../src/schema.js';
import {prepareImport,previewImport,commitPreparedImport} from '../src/migration/import-service.js';
import {loadVault,saveVaultAtomic} from '../src/storage/vault-store.js';
import {vaultDb} from '../test-support/vault-db.js';
function pack(){const v=emptyVault();v.personas=[{id:'p',name:'Synthetic'}];v.characters=[{id:'x',name:'Synthetic'}];v.stories=[{id:'s',title:'Synthetic package',personaId:'p',characterIds:['x']}];v.chats=[{id:'c',storyId:'s'}];const p={packageType:'velvet-vesper-native-story-package',packageVersion:'1.0',vesperSchemaVersion:1,importMode:'additive-only'};for(const [k,a] of Object.entries(v))if(Array.isArray(a))p[k]=a;return p;}
test('native story package prepares an additive preview without changing the source',()=>{const p=pack(),before=JSON.stringify(p),prepared=prepareImport(p);assert.equal(prepared.importMode,'merge');assert.equal(previewImport(p).counts.stories,1);assert.equal(JSON.stringify(p),before);});
test('additive save retains existing records; repeated package cannot overwrite or duplicate',async()=>{const db=vaultDb(),v=await loadVault(db);v.personas=[{id:'old-p',name:'Existing'}];v.characters=[{id:'old-x',name:'Existing'}];v.stories=[{id:'old-s',title:'Existing',personaId:'old-p',characterIds:['old-x'],settings:{model:'synthetic/model'}}];v.chats=[{id:'old-c',storyId:'old-s'}];await saveVaultAtomic(db,v);await commitPreparedImport(db,prepareImport(pack()),{expectedRevision:v.storageRevision});const fresh=await loadVault(db);assert.deepEqual(fresh.stories[0],v.stories[0]);assert.equal(fresh.stories.length,2);const before=JSON.stringify(fresh);await assert.rejects(commitPreparedImport(db,prepareImport(pack()),{expectedRevision:fresh.storageRevision}));assert.equal(JSON.stringify(await loadVault(db)),before);});
test('malformed, incompatible and destructive packages fail before save',()=>{for(const mutate of [p=>delete p.memoryEntries,p=>p.importMode='replace',p=>p.packageVersion='999',p=>p.stories[0].personaId='missing']){const p=pack();mutate(p);assert.throws(()=>prepareImport(p));assert.equal(previewImport(p).valid,false);}});
test('stale package save cannot replace newer data',async()=>{const db=vaultDb(),v=await loadVault(db),revision=v.storageRevision;await saveVaultAtomic(db,v);const before=JSON.stringify(await loadVault(db));await assert.rejects(commitPreparedImport(db,prepareImport(pack()),{expectedRevision:revision}),e=>e.code==='VESPER_VAULT_CONFLICT');assert.equal(JSON.stringify(await loadVault(db)),before);});
