import {savePersona,assignPersona,archivePersona,activePersonaId,personaAssignments,prepareDevonHumanPersona} from '../personas/persona-store.js';
const fields=['age','species','appearance','anatomy','personality','history','abilities','relationships','preferences','hardLimits','permanentCanon'];
const element=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
export function mountPersonas({host,getSnapshot,commit,isBusy,onError}){
 let editing=null;
 const error=message=>{let alert=host.querySelector("[role=alert]");if(!alert){alert=element("p");alert.setAttribute("role","alert");host.prepend(alert);}alert.textContent=message;onError(message);};
 const button=(text,action)=>{const b=element('button',text);b.type='button';b.className='ghost';b.onclick=async()=>{try{if(isBusy())throw new Error('Wait until the current operation finishes.');await action();}catch(e){error(e.message);}};return b;};
 async function persist(candidate){await commit(candidate);render();}
 function form(persona){editing=persona;host.replaceChildren();host.append(element('h2',persona?'Edit protagonist':'Create protagonist'));
  const f=element('form');f.className='persona-form';const inputs={};
  for(const key of ['name','folder','tags',...fields,'customFields']){const label=element('label',key==='hardLimits'?'Hard limits (one per line)':key==='permanentCanon'?'Permanent canon (one per line)':key==='customFields'?'Custom fields (JSON object)':key[0].toUpperCase()+key.slice(1));const input=element(['name','folder','tags','age','species'].includes(key)?'input':'textarea');input.name=key;input.value=key==='customFields'?JSON.stringify(persona?.profile?.customFields||{},null,2):key==='tags'?(persona?.tags||[]).join(', '):['hardLimits','permanentCanon'].includes(key)?(Array.isArray(persona?.profile?.[key])?persona.profile[key].join('\n'):persona?.profile?.[key]||''):(typeof(persona?.[key]??persona?.profile?.[key])==='object'?JSON.stringify(persona?.[key]??persona?.profile?.[key],null,2):String(persona?.[key]??persona?.profile?.[key]??''));input.dataset.initialValue=input.value;inputs[key]=input;label.append(input);f.append(label);}
  const save=element('button','Save persona');save.type='submit';save.className='send';f.append(save,button('Cancel',()=>render()));
  f.onsubmit=async e=>{e.preventDefault();try{if(isBusy())throw new Error('Wait until the current operation finishes.');const v=getSnapshot().vault,profile={...(persona?.profile||{})};for(const key of fields)if(inputs[key].value!==inputs[key].dataset.initialValue||!persona)profile[key]=['hardLimits','permanentCanon'].includes(key)?inputs[key].value.split('\n').filter(x=>x.trim()):inputs[key].value;profile.customFields=JSON.parse(inputs.customFields.value||'{}');if(!profile.customFields||Array.isArray(profile.customFields)||typeof profile.customFields!=='object')throw new Error('Custom fields must be a JSON object.');const assignments=persona?personaAssignments(v,persona.id):[];const shared=assignments.length>1||assignments.some(s=>s.personaBinding?.shared);if(shared&&!confirm('This shared persona is assigned to stories. Apply these profile changes to all of them?'))return;await persist(savePersona(v,{...(persona||{}),name:inputs.name.value,folder:inputs.folder.value,tags:inputs.tags.value.split(',').map(x=>x.trim()).filter(Boolean),profile},{confirmShared:!!shared}));}catch(e){error(e.message);}};host.append(f);
 }
 function render(){editing=null;host.replaceChildren();const {vault,storyId}=getSnapshot();host.append(element('h2','My Personas'),element('p','Player-controlled protagonists only. Assign an independent copy to keep stories isolated; historical identities remain preserved.'),button('Create persona',()=>form(null)));
  if(storyId&&vault.characters.some(c=>vault.stories.find(s=>s.id===storyId)?.characterIds?.includes(c.id)&&c.name==='Devon Mercer'))host.append(button('Prepare Amanda’s human persona for Devon',()=>{if(confirm('Assign an independent Amanda human profile to this Devon story, preserving its previous protagonist and all story history?'))return persist(prepareDevonHumanPersona(getSnapshot().vault,storyId));}));
  const search=element('input');search.placeholder='Search names, folders or tags';search.setAttribute('aria-label','Search personas');host.append(search);const list=element('div');list.className='data-list';host.append(list);
  function fill(){list.replaceChildren();for(const p of vault.personas.filter(p=>!p.archived&&JSON.stringify([p.name,p.folder,p.tags]).toLowerCase().includes(search.value.toLowerCase()))){const card=element('article');card.className='data-card';card.append(element('strong',p.name),element('p',`${p.profile?.species||'Species not specified'} · ${p.folder||'Unfiled'}${activePersonaId(vault.stories.find(s=>s.id===storyId))===p.id?' · Assigned to this story':''}`),button('Edit',()=>form(p)),button('Duplicate',()=>{const copy=structuredClone(p);delete copy.id;delete copy.storyId;delete copy.versions;return persist(savePersona(getSnapshot().vault,{...copy,name:p.name+' copy'}));}),button('Archive / Delete',()=>{if(!confirm('Archive this persona if referenced by any story or history; otherwise delete it?'))return;return persist(archivePersona(getSnapshot().vault,p.id,{confirmed:true}));}));
   if(storyId)card.append(button('Assign independent copy to this story',()=>persist(assignPersona(getSnapshot().vault,storyId,p.id))),button('Reuse shared persona',()=>{if(confirm('Explicitly share this profile with this story? Profile edits may affect other assigned stories.'))return persist(assignPersona(getSnapshot().vault,storyId,p.id,{shared:true}));}));list.append(card);}
   for(const p of vault.personas.filter(p=>p.archived)){const row=element('article');row.className='data-card';row.append(element('strong',p.name+' (archived)'),button('Restore',()=>persist(savePersona(getSnapshot().vault,{...p,archived:false},{confirmShared:true}))));list.append(row);}
  }search.oninput=fill;fill();
 }
 return {open:render,get editing(){return editing;}};
}
