import {previewPhoneEvents,applyPhoneEvents,preparePhoneEventCommit} from '../phone/phone-event-import.js';
import {ensureStoryPhone,getPhoneContacts,openPrivateThread,updatePhoneThread,setContactDisplayName,markPhoneThreadRead,phoneUnreadCount} from '../phone/phone-state.js';
import {orderedPhoneMessages,isPhoneMessageUnread} from '../phone/phone-state.js';
import {scanPhoneHistory,resolvePhoneHistoryCandidate,applyPhoneHistory} from '../phone/phone-history.js';

const node=(tag,text,className)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;};
export function createStoryPhone({getSnapshot,commitCandidate,sendPhoneMessage,cancelStoryScroll,isBusy=()=>false,onError=()=>{}}) {
  const launcher=node('button','☎','story-phone-launcher');launcher.id='storyPhoneButton';launcher.type='button';launcher.setAttribute('aria-label','Open story phone');launcher.setAttribute('aria-haspopup','dialog');
  const badge=node('span','','phone-badge');launcher.append(badge);document.body.append(launcher);
  const overlay=node('div',undefined,'story-phone-overlay');overlay.id='storyPhoneOverlay';overlay.hidden=true;
  overlay.innerHTML='<section class="story-phone" role="dialog" aria-modal="true" aria-labelledby="phoneHeading"><header><h2 id="phoneHeading">Story Phone</h2><button id="phoneClose" type="button" aria-label="Close story phone">✕</button></header><nav aria-label="Phone sections"><button id="phoneChats" type="button">Chats</button><button id="phoneContacts" type="button">Contacts</button></nav><p id="phoneNotice" role="status" hidden></p><div id="phoneContent" class="phone-content"></div></section>';
  document.body.append(overlay);
  const sync=node('button','Sync Existing Messages','phone-sync-trigger');sync.id='phoneSync';sync.type='button';overlay.querySelector('nav').after(sync);
  const find=id=>overlay.querySelector('#'+id),content=find('phoneContent');
  const drafts=new Map(),selections=new Map();let storyId=null,threadId=null,tab='chats',editing=false,working=false,scrollState=null,previousFocus=null;
  let eventPreview=null,eventSelection=new Set(),checkpointDownloaded=false,checkpointSaved=false,historyGeneration=0;
  let historyPreview=null,historySelection=new Set(),historyResolutions={},resolvingKey=null,historyPage=0;
  const story=()=>getSnapshot().vault.stories.find(s=>s.id===storyId);
  const draftKey=()=>JSON.stringify([storyId,threadId]);
  const contacts=()=>getPhoneContacts(getSnapshot().vault,storyId);
  const label=id=>contacts().find(c=>c.id===id)?.displayName || getSnapshot().vault.characters.find(c=>c.id===id)?.name || getSnapshot().vault.personas.find(p=>p.id===id)?.name || 'Unavailable contact';
  function notice(text){find('phoneNotice').textContent=text;find('phoneNotice').hidden=!text;}
  function captureDraft(){const input=find('phoneMessageInput');if(input&&threadId)drafts.set(draftKey(),input.value);}
  function button(text,action){const b=node('button',text);b.type='button';b.onclick=()=>perform(action);return b;}
  async function perform(action){if(working||isBusy()){notice('Wait for the current request or save to finish.');if(overlay.hidden)onError('Wait for the current request or save to finish.');return;}working=true;notice('');try{await action();}catch(e){const message=e?.refreshRequired?'Newer data was saved. Reload to refresh before retrying.':e?.message||'Phone operation could not finish. Your saved data was kept.';notice(message);if(overlay.hidden)onError(message);}finally{working=false;}}
  async function save(next,revision){await commitCandidate(next,revision);}
  function clearPreview(){historyGeneration++;eventPreview=null;eventSelection=new Set();checkpointDownloaded=false;checkpointSaved=false;historyPage=0;historyPreview=null;historySelection=new Set();historyResolutions={};resolvingKey=null;}
  function focusHistorySelection(key){[...content.querySelectorAll('[data-history-select]')].find(el=>el.dataset.historySelect===key)?.focus({preventScroll:true});}
  function startSync(){historyPage=0;captureDraft();const snap=getSnapshot();historyPreview=scanPhoneHistory(snap.vault,storyId);historySelection=new Set(historyPreview.candidates.filter(c=>c.status==='ready').map(c=>c.key));historyResolutions={};resolvingKey=null;render();find('phoneHistoryPreview').focus({preventScroll:true});}
  const unrecoverable=c=>c.issues.some(i=>['recipients','continuation','time','delivery','sender'].includes(i));
  function renderHistoryResolution(candidate,card){
    const form=node('form',undefined,'phone-history-resolution'),values={identities:{}};
    for(const [name,id] of Object.entries(candidate.identities))if(!id){const l=node('label','Canonical identity for '+name),select=node('select');select.dataset.historyIdentity=name;select.required=true;select.append(new Option('Choose a source-supported identity',''));
      const persona=getSnapshot().vault.personas.find(p=>p.id===story().personaId);for(const c of [persona,...contacts().map(c=>({id:c.id,name:c.canonicalName}))])if(c)select.append(new Option(c.name,c.id));if(candidate.version===2)select.append(new Option('Create source-documented archival contact','__new__'));const nameInput=node('input');nameInput.dataset.historyContactName=name;nameInput.value=name;nameInput.maxLength=120;nameInput.hidden=true;nameInput.setAttribute('aria-label','Documented name for '+name);select.onchange=()=>{nameInput.hidden=select.value!=='__new__';};l.append(select,nameInput);form.append(l);}
    if(candidate.issues.includes('thread')){const l=node('label','Existing group confirmed by this source'),select=node('select');select.id='phoneHistoryTarget';select.required=true;select.append(new Option('Choose the matching group',''));for(const t of story().phone.threads.filter(t=>t.chatId===candidate.chatId&&t.kind==='group'))select.append(new Option(t.title,t.id));if(candidate.version===2)select.append(new Option('Create separate recovered archive','__archive__'));l.append(select);form.append(l);}
    if(candidate.issues.includes('repeat')||candidate.version===2){const l=node('label','This is a separate sent text, not a quotation or repeated mention.'),check=node('input');check.type='checkbox';check.id='phoneHistoryDistinct';check.required=candidate.issues.includes('repeat');l.prepend(check);form.append(l);}
    if(candidate.issues.includes('membership')){const l=node('label','I confirm the displayed historical recipients from the source, including exits and reentries.'),c=node('input');c.type='checkbox';c.id='phoneHistoryMembership';c.required=true;l.prepend(c);form.append(l);}
    const l=node('label','I confirm these identities and this conversation are supported by the source. This grants no additional recipients.'),check=node('input');check.type='checkbox';check.id='phoneHistoryEvidenceConfirm';check.required=true;l.prepend(check);form.append(l);
    if(candidate.version===2){const l=node('label','Resolve and include compatible matches using these same reviewed identities and historical recipients. Repeated or incomplete matches stay excluded.'),b=node('input');b.type='checkbox';b.id='phoneHistoryApplyCompatible';l.prepend(b);form.append(l);}
    const submit=node('button','Resolve match');submit.type='submit';submit.id='phoneHistoryResolveSave';form.append(submit,button('Cancel resolution',()=>{resolvingKey=null;render();focusHistorySelection(candidate.key);}));
    form.onsubmit=e=>{e.preventDefault();perform(()=>{values.newContacts=[];for(const el of form.querySelectorAll('[data-history-identity]')){if(el.value==='__new__'){const input=[...form.querySelectorAll('[data-history-contact-name]')].find(n=>n.dataset.historyContactName===el.dataset.historyIdentity);values.newContacts.push({label:el.dataset.historyIdentity,canonicalName:input.value});}else Object.defineProperty(values.identities,el.dataset.historyIdentity,{value:el.value,enumerable:true});}values.confirmed=check.checked;values.distinct=Boolean(form.querySelector('#phoneHistoryDistinct')?.checked);values.membershipConfirmed=Boolean(form.querySelector('#phoneHistoryMembership')?.checked);const target=form.querySelector('#phoneHistoryTarget')?.value;values.createGroup=target==='__archive__';values.targetThreadId=values.createGroup?undefined:target;resolvePhoneHistoryCandidate(getSnapshot().vault,candidate,values);historyResolutions[candidate.key]=values;historySelection.add(candidate.key);if(form.querySelector('#phoneHistoryApplyCompatible')?.checked){for(const c of historyPreview.candidates){if(c.key===candidate.key||unrecoverable(c)||c.issues.includes('repeat'))continue;const sameRecipients=JSON.stringify(c.participantLabels.map(n=>n.toLocaleLowerCase()).sort())===JSON.stringify(candidate.participantLabels.map(n=>n.toLocaleLowerCase()).sort());if(c.kind!==candidate.kind||c.kind==='group'&&c.conversationKey!==candidate.conversationKey||!sameRecipients)continue;const choice={...values,distinct:false,newContacts:values.newContacts.filter(n=>Object.keys(c.identities).some(label=>label.toLocaleLowerCase()===n.label.toLocaleLowerCase()))};try{resolvePhoneHistoryCandidate(getSnapshot().vault,c,choice);historyResolutions[c.key]=choice;historySelection.add(c.key);}catch{/* Keep unmatched or incomplete evidence unresolved. */}}}resolvingKey=null;render();focusHistorySelection(candidate.key);});};card.append(form);
  }
  function eventPackageLoader(preview){
    const label=node('label','Load a verified event ledger (optional)'),input=node('input');input.type='file';input.accept='.json,application/json';input.id='phoneEventPackage';label.append(input);preview.append(label);
    input.onchange=()=>perform(async()=>{const file=input.files?.[0];if(!file)return;if(file.size>32*1024*1024)throw new Error('The event ledger exceeds the 32 MB limit. Nothing was changed.');const generation=historyGeneration,targetStory=storyId;let data;try{data=JSON.parse(await file.text());}catch{throw new Error('The event ledger is incomplete or damaged. Nothing was changed.');}
      if(overlay.hidden||storyId!==targetStory||generation!==historyGeneration)return;
      if(data?.version!==1||!Array.isArray(data.entries)||data.entries.some(e=>e?.claim?.event?.storyId!==targetStory))throw new Error('Choose a verified ledger belonging only to this story. Nothing was changed.');
      const snap=getSnapshot();eventPreview=previewPhoneEvents(snap.vault,data);eventSelection=new Set(eventPreview.accepted.map(e=>e.claim.event.id));checkpointDownloaded=false;checkpointSaved=false;render();find('phoneHistoryPreview').focus({preventScroll:true});
    });
  }
  function selectedEventPreview(){return {...eventPreview,accepted:eventPreview.accepted.filter(e=>eventSelection.has(e.claim.event.id))};}
  function renderEventHistory(){
    const preview=node('section',undefined,'phone-history-preview');preview.id='phoneHistoryPreview';preview.tabIndex=-1;
    preview.append(node('h3','Verified historical send events'),node('p','Nothing is saved until you confirm. Only approved source events and historical audiences are eligible. Private messages never fall back to a group.'),node('p',`${eventPreview.accepted.length} accepted · ${eventPreview.duplicates.length} already present · ${eventPreview.excluded.length} excluded`));
    const groups=new Map();for(const entry of eventPreview.accepted){const id=entry.claim.event.conversationId;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(entry);}
    for(const entries of groups.values()){
      const c=entries[0].claim,section=node('section',undefined,'phone-history-candidate'),label=node('label',`${c.title} — ${entries.length} events`),check=node('input');check.type='checkbox';check.checked=entries.every(e=>eventSelection.has(e.claim.event.id));check.onchange=()=>{for(const e of entries)check.checked?eventSelection.add(e.claim.event.id):eventSelection.delete(e.claim.event.id);render();};label.prepend(check);section.append(label,node('small','Originating chat: '+c.event.chatId+' · '+(c.kind==='private'?'Private recipients only':'Historical membership retained per send')));
      const detail=node('details');detail.append(node('summary','Optional individual exclusions and source evidence'));
      for(const entry of entries){const e=entry.claim.event,card=node('article',undefined,'phone-history-candidate'),l=node('label',e.senderLabel),select=node('input');select.type='checkbox';select.checked=eventSelection.has(e.id);select.dataset.eventSelect=e.id;select.onchange=()=>{select.checked?eventSelection.add(e.id):eventSelection.delete(e.id);find('phoneEventConfirm').disabled=!eventSelection.size||!checkpointSaved;};l.prepend(select);card.append(l,node('p',e.text,'phone-history-text'),node('small',`Event ${e.id} · PDF pages ${e.physicalPdfPages.join(', ')} · Source ${e.sourceMessageId}:${e.start}–${e.end}`),node('small','Historical recipients: '+entry.claim.audienceIds.map(id=>labelForEvent(id,entry.claim)).join(' · ')));detail.append(card);}
      section.append(detail);preview.append(section);
    }
    if(eventPreview.excluded.length){const detail=node('details');detail.append(node('summary','Excluded events — cannot be selected'));for(const e of eventPreview.excluded)detail.append(node('p',(e.eventId||'Unknown event')+': '+e.reason));preview.append(detail);}
    const download=button('Download verified rollback backup',async()=>{const generation=historyGeneration,snap=getSnapshot(),prepared=await preparePhoneEventCommit(snap.vault,selectedEventPreview(),{confirmed:true});if(overlay.hidden||generation!==historyGeneration)return;const url=URL.createObjectURL(new Blob([prepared.checkpoint],{type:'application/json'})),a=node('a');a.href=url;a.download='Vesper_Before_Phone_Recovery.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);checkpointDownloaded=true;render();});download.id='phoneEventBackup';preview.append(download);
    const savedLabel=node('label','I saved the verified rollback backup'),saved=node('input');saved.type='checkbox';saved.id='phoneEventBackupSaved';saved.disabled=!checkpointDownloaded;saved.checked=checkpointSaved;saved.onchange=()=>{checkpointSaved=saved.checked;find('phoneEventConfirm').disabled=!eventSelection.size||!checkpointSaved;};savedLabel.prepend(saved);const savedRow=node('div',undefined,'phone-history-candidate');savedRow.append(savedLabel);preview.append(savedRow);
    const controls=node('div',undefined,'phone-history-actions'),cancel=button('Cancel',()=>{clearPreview();render();sync.focus({preventScroll:true});});cancel.id='phoneHistoryCancel';controls.append(cancel);
    const confirm=button('Confirm selected historical events',async()=>{if(!checkpointDownloaded||!checkpointSaved)throw new Error('Save the verified rollback backup first. Nothing was changed.');const snap=getSnapshot(),selected=selectedEventPreview(),next=applyPhoneEvents(snap.vault,selected,{confirmed:true});await save(next,selected.baseRevision);clearPreview();render();notice('Verified historical events saved. No AI request was made.');if(!overlay.hidden)sync.focus({preventScroll:true});});confirm.id='phoneEventConfirm';confirm.disabled=!eventSelection.size||!checkpointSaved;controls.append(confirm);preview.append(controls);content.append(preview);
  }
  function labelForEvent(id,claim){return claim.contacts.find(c=>c.id===id)?.canonicalName||getSnapshot().vault.characters.find(c=>c.id===id)?.name||getSnapshot().vault.personas.find(p=>p.id===id)?.name||id;}
  function renderHistory(){
    if(eventPreview){renderEventHistory();return;}
    const preview=node('section',undefined,'phone-history-preview');preview.id='phoneHistoryPreview';preview.tabIndex=-1;preview.append(node('h3','Review recovered texts'),node('p','Nothing is saved until you confirm. Source order is preserved; unknown send times and missing recipients are never inferred.'),node('p',`${historyPreview.duplicateCount} already recovered · ${historyPreview.candidates.length} matches to review`));
    eventPackageLoader(preview);
    for(const [status,title,id] of [['ready','Recoverable messages','phoneHistoryReady'],['uncertain','Uncertain matches — explicit resolution required','phoneHistoryUncertain']]){
      const section=node('section');section.id=id;section.append(node('h4',title));
      for(const candidate of historyPreview.candidates.slice(historyPage*100,(historyPage+1)*100).filter(c=>c.status===status)){
        const card=node('article',undefined,'phone-history-candidate');card.dataset.historyCandidate=candidate.key;
        const include=node('label','Include this message'),check=node('input');check.type='checkbox';check.dataset.historySelect=candidate.key;check.checked=historySelection.has(candidate.key);check.disabled=unrecoverable(candidate);check.onchange=()=>{check.checked?historySelection.add(candidate.key):historySelection.delete(candidate.key);render();[...content.querySelectorAll('[data-history-select]')].find(el=>el.dataset.historySelect===candidate.key)?.focus({preventScroll:true});};include.prepend(check);card.append(include,node('strong',candidate.senderLabel+' → '+(candidate.participantLabels.join(', ')||'Recipients unknown')),node('p',candidate.text,'phone-history-text'));
        const chat=getSnapshot().vault.chats.find(c=>c.id===candidate.chatId);card.append(node('small',(chat?.title||candidate.chatId)+' · '+(candidate.timestampText||'Time unknown')));
        const source=node('details'),summary=node('summary','View source excerpt'),excerpt=node('pre',candidate.excerpt);source.append(summary,excerpt);card.append(source);
        if(status==='uncertain'){
          card.append(node('p',unrecoverable(candidate)?'Incomplete recipients, ambiguous text boundaries, unsupported time notation, or unconfirmed delivery: excluded until the source can establish a complete sent exchange.':'Review required: '+candidate.issues.join(', ')));
          if(!unrecoverable(candidate)){const resolved=historyResolutions[candidate.key];if(resolved){const mappings=Object.entries(resolved.identities).map(([name,id])=>name+' → '+(getSnapshot().vault.characters.find(c=>c.id===id)?.name||getSnapshot().vault.personas.find(p=>p.id===id)?.name));card.append(node('small','Explicitly resolved'+(mappings.length?': '+mappings.join(' · '):'')));if(resolved.targetThreadId)card.append(node('small','Reviewed group: '+story().phone.threads.find(t=>t.id===resolved.targetThreadId)?.title));}const resolve=button('Resolve match',()=>{resolvingKey=candidate.key;render();content.querySelector('.phone-history-resolution select, .phone-history-resolution input')?.focus({preventScroll:true});});resolve.dataset.historyResolve=candidate.key;card.append(resolve);if(resolvingKey===candidate.key)renderHistoryResolution(candidate,card);}
        }
        section.append(card);
      }
      preview.append(section);
    }
    if(historyPreview.candidates.length>100){const pages=node('div');pages.append(node('p',`Page ${historyPage+1} of ${Math.ceil(historyPreview.candidates.length/100)} — selections are retained.`));if(historyPage>0)pages.append(button('Previous matches',()=>{historyPage--;resolvingKey=null;render();}));if((historyPage+1)*100<historyPreview.candidates.length)pages.append(button('Next matches',()=>{historyPage++;resolvingKey=null;render();}));preview.append(pages);}
    const controls=node('div',undefined,'phone-history-actions');controls.append(button('Cancel',()=>{clearPreview();render();sync.focus({preventScroll:true});}));controls.firstChild.id='phoneHistoryCancel';
    const confirm=button('Confirm selected messages',async()=>{const snap=getSnapshot(),next=applyPhoneHistory(snap.vault,historyPreview,{confirmed:true,selectedKeys:[...historySelection],resolutions:historyResolutions});if(next!==snap.vault)await save(next,historyPreview.baseRevision);clearPreview();render();notice('Selected historical messages saved. No AI request was made.');if(!overlay.hidden)sync.focus({preventScroll:true});});confirm.id='phoneHistoryConfirm';confirm.disabled=!historySelection.size||historyPreview.candidates.some(c=>historySelection.has(c.key)&&c.status==='uncertain'&&!historyResolutions[c.key]);controls.append(confirm);preview.append(controls);content.append(preview);
  }
  async function viewThread(id){captureDraft();threadId=id;selections.set(storyId,id);tab='chats';editing=false;
    const snap=getSnapshot(),s=story(),t=s?.phone?.threads.find(t=>t.id===id);
    if(t?.messages.some(m=>isPhoneMessageUnread(m,t))&&!isBusy())await save(markPhoneThreadRead(snap.vault,storyId,id),snap.revision);
    render();}
  function renderContacts(){for(const c of contacts()){
    const row=node('section',undefined,'phone-contact');const open=button(c.displayName,async()=>{const snap=getSnapshot();const result=openPrivateThread(snap.vault,storyId,snap.chatId,c.id);if(JSON.stringify(result.vault)!==JSON.stringify(snap.vault))await save(result.vault,snap.revision);await viewThread(result.threadId);});open.dataset.phoneContact=c.id;
    const canonical=node('small',c.canonicalName);const name=node('input');name.value=story().phone.contactDisplayNames[c.id]||'';name.placeholder='Contact nickname';name.maxLength=120;name.dataset.phoneNickname=c.id;name.setAttribute('aria-label','Nickname for '+c.canonicalName);
    const update=button('Save nickname',async()=>{const snap=getSnapshot();await save(setContactDisplayName(snap.vault,storyId,c.id,name.value),snap.revision);render();});update.dataset.phoneNicknameSave=c.id;
    row.append(open,canonical,name,update);content.append(row);
  }if(!contacts().length)content.append(node('p','No character contacts in this story.'));}
  function renderList(){const threads=story()?.phone?.threads||[];
    for(const t of threads){const unread=t.messages.filter(m=>isPhoneMessageUnread(m,t)).length,latest=orderedPhoneMessages(t).at(-1);
      const row=button('',()=>viewThread(t.id));row.className='phone-thread-row';row.dataset.phoneThread=t.id;
      row.append(node('strong',t.kind==='private'&&!t.historicalOnly?label(t.participantIds[0]):t.title),node('small',t.participantIds.map(label).join(' · ')),node('span',latest?.text.slice(0,100)||'No messages yet.'));
      const chat=getSnapshot().vault.chats.find(c=>c.id===t.chatId);row.append(node('small',(chat?.title||'Story conversation '+(getSnapshot().vault.chats.filter(c=>c.storyId===storyId).findIndex(c=>c.id===t.chatId)+1))+' · '+(latest?.recovery?(latest.recovery.timestampText||'Time unknown'):latest?.createdAt?new Date(latest.createdAt).toLocaleString():'')));
      if(unread)row.append(node('span',String(unread)+' unread','phone-unread'));content.append(row);
    }if(!threads.length)content.append(node('p','No chats yet. Open Contacts to start a conversation.'));
  }
  function renderEditor(t){const form=node('form',undefined,'phone-group-editor');
    const titleLabel=node('label','Group name');const title=node('input');title.id='phoneGroupTitle';title.value=t.title;title.maxLength=120;title.required=true;titleLabel.append(title);form.append(titleLabel);
    for(const c of contacts().filter(c=>!c.archiveOnly)){const l=node('label',undefined,'phone-member');const checkbox=node('input');checkbox.type='checkbox';checkbox.dataset.phoneMember=c.id;checkbox.checked=t.participantIds.includes(c.id);l.append(checkbox,node('span',c.displayName));form.append(l);}
    const submit=node('button','Save group');submit.id='phoneSaveGroup';submit.type='submit';form.append(submit,button('Cancel',()=>{editing=false;render();}));
    form.onsubmit=e=>{e.preventDefault();perform(async()=>{const snap=getSnapshot(),ids=[...form.querySelectorAll('input[type=checkbox]:checked')].map(c=>c.dataset.phoneMember);await save(updatePhoneThread(snap.vault,storyId,t.id,{title:title.value,participantIds:ids}),snap.revision);editing=false;render();});};content.append(form);
  }
  function renderThread(t){const head=node('div',undefined,'phone-thread-heading');const back=button('Back',()=>{captureDraft();threadId=null;selections.delete(storyId);render();});
    const title=node('h3',t.kind==='private'&&!t.historicalOnly?label(t.participantIds[0]):t.title);title.id='phoneThreadTitle';title.dataset.threadId=t.id;head.append(back,title);
    if(t.kind==='group'&&!t.historicalOnly){const edit=button('Edit group',()=>{captureDraft();editing=true;render();});edit.id='phoneEditGroup';head.append(edit);}content.append(head);
    if(editing){renderEditor(t);return;}
    const transcript=node('div',undefined,'phone-transcript');transcript.setAttribute('role','log');transcript.setAttribute('aria-label','Phone messages');
    let recovered=false,native=false;for(const m of orderedPhoneMessages(t)){if(m.recovery&&!recovered){transcript.append(node('p','Recovered transcript history — source order; timing relative to live phone messages is unverified.','phone-history-divider'));recovered=true;}if(!m.recovery&&recovered&&!native){transcript.append(node('p','Live phone messages','phone-history-divider'));native=true;}const bubble=node('article',undefined,'phone-bubble '+m.senderType);bubble.append(node('strong',label(m.senderId)),node('p',m.text),node('small',m.recovery?(m.recovery.timestampText||'Time unknown'):new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})));transcript.append(bubble);}content.append(transcript);
    if(t.historicalOnly){content.append(node('p','Source-backed historical archive. No AI generation is available for archival contacts.'));transcript.scrollTop=transcript.scrollHeight;return;}
    const form=node('form',undefined,'phone-composer'),input=node('textarea');input.id='phoneMessageInput';input.placeholder='Write a text message…';input.setAttribute('aria-label','Phone message');input.rows=2;input.maxLength=10000;input.value=drafts.get(draftKey())||'';input.oninput=()=>drafts.set(draftKey(),input.value);
    const send=node('button','Send');send.type='submit';send.id='phoneSend';const more=button('Continue',()=>dispatch('', 'continue'));more.id='phoneContinue';send.disabled=isBusy();more.disabled=isBusy();form.append(input,send,more);
    form.onsubmit=e=>{e.preventDefault();perform(()=>dispatch(input.value,'send'));};content.append(form);
    transcript.scrollTop=transcript.scrollHeight;
  }
  async function dispatch(text,action){captureDraft();const targetStory=storyId,targetThread=threadId;
    if(action==='send'&&!text.trim()){notice('Write a message first.');return;}
    try{await sendPhoneMessage({storyId:targetStory,threadId:targetThread,text,action,onSubmitted:()=>{notice('Vesper is replying…');if(action==='send'){drafts.delete(JSON.stringify([targetStory,targetThread]));if(storyId===targetStory&&threadId===targetThread){const input=find('phoneMessageInput');if(input)input.value='';}}if(storyId===targetStory&&threadId===targetThread)render();},isViewed:()=>!overlay.hidden&&storyId===targetStory&&threadId===targetThread&&tab==='chats'});notice('');}finally{if(!overlay.hidden)render();}
  }
  function render(){if(overlay.hidden)return;content.replaceChildren();content.classList.toggle('phone-thread-content',!historyPreview&&tab==='chats'&&Boolean(threadId));sync.hidden=Boolean(historyPreview);find('phoneHeading').textContent=(story()?.title||'Story')+' · Phone';
    find('phoneChats').setAttribute('aria-pressed',String(tab==='chats'));find('phoneContacts').setAttribute('aria-pressed',String(tab==='contacts'));
    if(historyPreview)renderHistory();else if(tab==='contacts')renderContacts();else {const t=story()?.phone?.threads.find(t=>t.id===threadId);if(t)renderThread(t);else{threadId=null;renderList();}}refreshBadge();}
  function refreshBadge(){const snap=getSnapshot(),s=snap.vault?.stories.find(s=>s.id===snap.storyId),count=phoneUnreadCount(s);badge.textContent=count>99?'99+':String(count);badge.hidden=!count;launcher.hidden=!snap.storyVisible||!snap.storyId;launcher.setAttribute('aria-label','Open story phone'+(count?`, ${count} unread`:''));}
  function resize(){if(overlay.hidden)return;const vv=window.visualViewport;overlay.style.top=(vv?.offsetTop||0)+'px';overlay.style.height=(vv?.height||window.innerHeight)+'px';}
  async function open(){await perform(async()=>{const snap=getSnapshot();if(!snap.storyVisible||!snap.storyId||!snap.chatId)return;
    const next=ensureStoryPhone(snap.vault,snap.storyId,snap.chatId);if(JSON.stringify(next)!==JSON.stringify(snap.vault))await save(next,snap.revision);
    if(getSnapshot().storyId!==snap.storyId||!getSnapshot().storyVisible)return;
    storyId=snap.storyId;threadId=selections.get(storyId)||null;tab='chats';editing=false;previousFocus=document.activeElement;cancelStoryScroll();
    scrollState={x:scrollX,y:scrollY,bodyStyle:document.body.getAttribute('style'),pane:document.getElementById('messages')?.scrollTop||0};
    document.body.style.position='fixed';document.body.style.top=-scrollState.y+'px';document.body.style.left=-scrollState.x+'px';document.body.style.width='100%';document.body.style.overflow='hidden';
    overlay.hidden=false;resize();if(threadId)await viewThread(threadId);else render();find('phoneClose').focus({preventScroll:true});
  });}
  function close(){if(overlay.hidden)return;captureDraft();clearPreview();overlay.hidden=true;
    if(scrollState){if(scrollState.bodyStyle===null)document.body.removeAttribute('style');else document.body.setAttribute('style',scrollState.bodyStyle);window.scrollTo(scrollState.x,scrollState.y);const pane=document.getElementById('messages');if(pane)pane.scrollTop=scrollState.pane;scrollState=null;}
    if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});refreshBadge();}
  function refresh(){refreshBadge();if(!overlay.hidden){const snap=getSnapshot();if(!snap.storyVisible||snap.storyId!==storyId)close();}}
  const keydown=e=>{if(overlay.hidden)return;if(e.key==='Escape'){e.preventDefault();close();}else if(e.key==='Tab'){const items=[...overlay.querySelectorAll('button,input,textarea,select,summary')].filter(el=>!el.disabled&&el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  launcher.onclick=open;find('phoneClose').onclick=close;sync.onclick=()=>perform(startSync);find('phoneChats').onclick=()=>perform(()=>{captureDraft();clearPreview();tab='chats';threadId=null;editing=false;render();});find('phoneContacts').onclick=()=>perform(()=>{captureDraft();clearPreview();tab='contacts';editing=false;render();});
  overlay.addEventListener('click',e=>{if(e.target===overlay)close();});document.addEventListener('keydown',keydown);window.visualViewport?.addEventListener('resize',resize);window.visualViewport?.addEventListener('scroll',resize);window.addEventListener('resize',resize);refreshBadge();
  return {open,close,refresh,destroy(){close();launcher.remove();overlay.remove();document.removeEventListener('keydown',keydown);window.visualViewport?.removeEventListener('resize',resize);window.visualViewport?.removeEventListener('scroll',resize);window.removeEventListener('resize',resize);}};
}
