import { emptyVault, validateVault, normalizeVault } from "../schema.js";
export const VESPER_DB_NAME="velvet-vesper";export const VESPER_DB_VERSION=1;const STORE="vault";
function requestAsPromise(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function transactionDone(t){return new Promise((resolve,reject)=>{t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error("Transaction aborted."));});}
export async function openVesperDb(){if(!globalThis.indexedDB)throw new Error("IndexedDB is unavailable on this device.");const r=indexedDB.open(VESPER_DB_NAME,VESPER_DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);};return requestAsPromise(r);}
export async function loadVault(db){const tx=db.transaction(STORE,"readonly");const raw=await requestAsPromise(tx.objectStore(STORE).get("active"));await transactionDone(tx);if(!raw)return emptyVault();const validation=validateVault(raw);if(!validation.ok)throw new Error(`Invalid Vesper vault: ${validation.errors.join(" ")}`);return normalizeVault(raw);}
export async function saveVaultAtomic(db,vault){const normalized=normalizeVault(vault),validation=validateVault(normalized);if(!validation.ok)throw new Error(`Refusing to save invalid vault: ${validation.errors.join(" ")}`);const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(structuredClone(normalized),"active");await transactionDone(tx);return normalized;}
export async function replaceVaultAtomic(db,nextVault,{expectedSchemaVersion=1}={}){if(nextVault.schemaVersion!==expectedSchemaVersion)throw new Error("Schema version changed during import; active vault was not modified.");return saveVaultAtomic(db,nextVault);}
export async function clearVault(db){const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete("active");await transactionDone(tx);}
